### ISSUE TITLE
19.6.2. How to activate a particular implementation?

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1065]
$ pip install --user git+https://github.com/d2l-ai/d2l-book

  Building wheel for d2lbook (setup.py) ... done
  Created wheel for d2lbook: filename=d2lbook-0.1.16-py3-none-any.whl size=45335 sha256=b8dc8e4e0f672849f54dc05c008db79c8e3282605306e4035f0c47bc1fc7a1b8
  Stored in directory: C:\Users\a8679\AppData\Local\Temp\pip-ephem-wheel-cache-4t0dup_k\wheels\2b\cf\1b\550addc9241a37aebb7bf36b1bede46424521ac56aed39c917
Successfully built d2lbook

$ pip list | grep d2lbook
d2lbook                            0.1.16

$ d2lbook activate pytorch chapter_multilayer-perceptrons/mlp-scratch.md
**bash: d2lbook: command not found**

**Comment by mli** [comment]
does `d2lbook: command not found` mean `d2lbook` not found or `activate` not found. For the latter, I bumped version to 0.1.17, you can install d2lbook again to check if you have the 0.1.17 installed

**Comment by StevenJokes** [comment]
Installing collected packages: d2lbook
  Attempting uninstall: d2lbook
    Found existing installation: d2lbook 0.1.16
    Uninstalling d2lbook-0.1.16:
      Successfully uninstalled d2lbook-0.1.16
Successfully installed d2lbook-0.1.17


a8679@LAPTOP-8UNNKSEA MINGW64 /d/onedrive/文档/code/DL/d2l-en        
$ d2lbook activate pytorch chapter_multilayer-perceptrons/mlp-scratc
h.md
**[d2lbook:config.py:L59] CRITICAL Failed to find the index file: .\index.md**

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/88387010-3134c180-cde4-11ea-8948-969951acfaed.png)
How to fix it?

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/88388286-ce90f500-cde6-11ea-958c-624517d28a8f.png)
I think it is caused by 
![image](https://user-images.githubusercontent.com/25657787/88388308-d6509980-cde6-11ea-8ef1-0ac7eb8690cb.png)

**Comment by StevenJokes** [comment]
It is well now!
![image](https://user-images.githubusercontent.com/25657787/88388649-83c3ad00-cde7-11ea-84d9-d27a136f9693.png)

**Comment by StevenJokes** [comment]
I think it maybe has relation about operation system?
