### ISSUE TITLE
typo in section 6.3.1

### ISSUE THREAD

**Issue by alexanderchr** [d2l-ai/d2l-en#1094]
In section 6.3.1,

> Assuming that k_h is even here, we will pad p_h/2 rows on both sides of the height. If k_h is odd, one possibility is to pad p_h/2 rows on the top of the input and p_h/3 rows on the bottom. We will pad both sides of the width in the same way.

I think it should be "if p_h is even/odd", not k_h, since p_h will be odd if k_h is even and conversely.

**Comment by StevenJokes** [comment]
You are right.The Chinese version is the version.

**Comment by StevenJokes** [comment]
Can you close?

**Comment by alexanderchr** [comment]
thanks!
