### ISSUE TITLE
add a feature:Click Chinese button just like what pytorch and mxnet to return words of the Chinese version.

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1108]

**Comment by StevenJokes** [comment]
It means that we don't need another third level domain.
But it maybe cause that the docs is too long and hard to compare...So I dropped this idea.

**Comment by StevenJokes** [comment]
But I still think that it is worth to try to add a button to shift to Chinese words . And it means that everyone needs to understand English annotations in three forms of code. Maybe it will give Chinese readers a chance to start smoothly  by Chinese, and dive easily by English.

**Comment by astonzhang** [comment]
Thanks. For now, we think it makes our workflow much easier when splitting multi-lang into different repos.
