### ISSUE TITLE
[pytorch]4.4 has a bug in preview version. PR in #1117

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1116]
<img width="1199" alt="bug" src="https://user-images.githubusercontent.com/25657787/86527305-46e35500-bed0-11ea-9487-a78efd0a842a.png">
fix it in 8th cell:
https://github.com/StevenJokes/D2L_enread/blob/39eed9751b195d14da685c8374e992045b2fc19e/Ch04_MP/4-4-new.ipynb

**Comment by StevenJokes** [comment]
I have found it in
<img width="798" alt="no_bug" src="https://user-images.githubusercontent.com/25657787/86527456-72b30a80-bed1-11ea-96a4-130e3d95284c.png">
https://github.com/d2l-ai/d2l-en/blob/master/chapter_multilayer-perceptrons/underfit-overfit.md
why doesn't it appear in my preview version?

**Comment by StevenJokes** [comment]
It didn't happen too in http://preview.d2l.ai/d2l-en/PR-1115/chapter_multilayer-perceptrons/underfit-overfit.html.

**Comment by StevenJokes** [comment]
I got it! we forget to change `all` to `mxnet`!

**Comment by StevenJokes** [comment]
Have PR in https://github.com/d2l-ai/d2l-en/issues/1116 ！

**Comment by StevenJokes** [comment]
`#tab pytorch` and `#tab mxnet` lost their functions because of  `#tab all`.
![image](https://user-images.githubusercontent.com/25657787/86527766-a93e5480-bed4-11ea-8fad-a7f167804911.png)
![image](https://user-images.githubusercontent.com/25657787/86527803-eb679600-bed4-11ea-9169-a2332347780f.png)

**Comment by StevenJokes** [comment]
It tells us not to use `#@tab all` abusively

**Comment by StevenJokes** [comment]
In `#tab all`  situation, 
![image](https://user-images.githubusercontent.com/25657787/86697286-d3ad2080-c040-11ea-8e9e-3ae3215043b2.png)
You can look 6th cell in https://github.com/StevenJokes/D2L_enread/blob/39eed9751b195d14da685c8374e992045b2fc19e/Ch04_MP/4-4-new.ipynb

**Comment by astonzhang** [comment]
@AnirudhDagar can you take a look?

**Comment by AnirudhDagar** [comment]
I've already looked at this issue and PR #1117 @astonzhang!
@StevenJokes can you please mention the exact issue clearly?
I don't understand what problem you are facing here.

Everything looks good to me, other than #1105 which we are looking into.

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/86861784-783f6900-c0fa-11ea-971f-693cacf8206d.png)
![image](https://user-images.githubusercontent.com/25657787/86861791-7c6b8680-c0fa-11ea-9200-2aa15ec5b110.png)
@astonzhang  `@#tab all`覆盖了 `@#tab pytorch`和`@#tab tensorflow`的内容，6楼的能运行，这个有bug.
@AnirudhDagar  In 4.4.4.1, `@#tab pytorch` was covered by `@#tab all`. Please try to run the pytorch code in http://preview.d2l.ai/d2l-en/PR-1132/chapter_multilayer-perceptrons/underfit-overfit.html. You will get it.

**Comment by terrytangyuan** [comment]
I don't understand the issue you are having either. I don't see any issues in the preview.

**Comment by StevenJokes** [comment]
@terrytangyuan 您从头跑一遍程序，其他非1117的preview里，tensorflow和pytorch都只显示这个内容
![image](https://user-images.githubusercontent.com/25657787/86916495-42c86900-c156-11ea-842c-befeda8497de.png)
而不是
![image](https://user-images.githubusercontent.com/25657787/86916547-57a4fc80-c156-11ea-9484-e55cf467b9dd.png)

**Comment by terrytangyuan** [comment]
Okay feel free to close it if it's no longer an issue. Thanks.

**Comment by StevenJokes** [comment]
But I think that it is better to use common words other than annotatation in code. 
The whole book has a style which there is always some sentences before code cell.
So I have a habit to copy the following code, thus I missed the line.
What's your point?

**Comment by StevenJokes** [comment]
Anyway. My mistake.
