### ISSUE TITLE
Unnecessary output <tensorflow.python.keras.engine.sequential.Sequential at 0x7fd94cc7aa50>

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-en#1125]
http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_convolutional-neural-networks/lenet.html

Is there a way to avoid printing unnecessary output for train_ch6 (and possibly other similar functions):
<tensorflow.python.keras.engine.sequential.Sequential at 0x7fd94cc7aa50>

@terrytangyuan

**Comment by abhinavsp0730** [comment]
Hey, @astonzhang it's not the training output. I think the train_ch6 function is having a return statement. So while calling the model it's returning the model and thats why it's printing the address of the model.
How, about making the train_ch6 without a return statement. @astonzhang @terrytangyuan does it work?

**Comment by astonzhang** [comment]
Hiding the return statement will be ideal.

**Comment by terrytangyuan** [comment]
The `return` is necessary since we are creating the model object inside the function the model will be used outside of the function scope. We can assign the function output to a local variable to hide it.

**Comment by astonzhang** [comment]
Sure, can we just hide it from the output?

**Comment by astonzhang** [comment]
Reason for closure: https://github.com/d2l-ai/d2l-en/pull/1221
