### ISSUE TITLE
[pytorch]Some questions in torch.py.

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1141]
https://github.com/d2l-ai/d2l-en/commit/7a6d2973f85274f2e11cb6286bb68955254cc693#diff-7199ea3162d85ba4377898f52160727b

![image](https://user-images.githubusercontent.com/25657787/86955566-5d1c3a00-c18a-11ea-83ab-fb83a6f9dd3c.png)

![image](https://user-images.githubusercontent.com/25657787/86955734-a3719900-c18a-11ea-883b-08f38076a18d.png)

**Comment by StevenJokes** [comment]
Please fix it quickly! @mli @astonzhang @AnirudhDagar

**Comment by StevenJokes** [comment]
It also happens in mxnet.py and tensorflow.py, so it maybe influences all eval process.
I reinstall my system, and lost d2l old version. But I will not install d2l until it fixed.

**Comment by StevenJokes** [comment]
prod!

**Comment by StevenJokes** [comment]
No answer...

**Comment by goldmermaid** [comment]
Hi @StevenJokes , please refer to the latest updates: https://github.com/d2l-ai/d2l-en/blob/master/d2l/torch.py.

Let us know if that solve your questions.

**Comment by StevenJokes** [comment]
It didn't. 
![image](https://user-images.githubusercontent.com/25657787/87458505-acf07a80-c63c-11ea-8567-54333b170c3b.png)
in https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html 
![image](https://user-images.githubusercontent.com/25657787/87458415-86324400-c63c-11ea-881d-1f789ac1c5ac.png)

**Comment by StevenJokes** [comment]
The function was saved in torch.py, tensorflow.py, mxnet.py.
I have to PR first.

**Comment by StevenJokes** [comment]
OK. PR all related.

**Comment by astonzhang** [comment]
See my comments in https://github.com/d2l-ai/d2l-en/pull/1176
