### ISSUE TITLE
[pytorch]just complete pytorch android demo app.

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1155]
There are some ** bugs**  not shown in [PyTorch Mobile Runtime for Android](https://www.youtube.com/watch?v=O_2KBhkIvnc&list=PL_lsbAsL_o2CltIzzbaS_j1q1Lcvdyjsg&index=5&t=0s)
My github repo:https://github.com/StevenJokes/pytorch-andriod-greatdemo
My blog:https://blog.dltech.xyz/post/pytorch-android/

**Comment by astonzhang** [comment]
Please use Issues to report issues. Thanks.
