### ISSUE TITLE
Add a feature:cite not only section num but also title.

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1167]
![image](https://user-images.githubusercontent.com/25657787/87381920-5cd7d080-c5c8-11ea-8157-23bad9a8625a.png)
![image](https://user-images.githubusercontent.com/25657787/87381939-69f4bf80-c5c8-11ea-85d9-39eedb4bb05e.png)
Just like the Chinese version, we need to add title of cited section, in order to have a better recall of memory.

**Comment by astonzhang** [comment]
In academic writing, it's common to refer to section numbers.

**Comment by StevenJokes** [comment]
OK, I got it.
