### ISSUE TITLE
Doc string for dataloader in "image-classification-dataset" part

### ISSUE THREAD

**Issue by SportsTHU** [d2l-ai/d2l-en#1211]
Dear Professor/authors:
  I am not sure whether I've mis-understood the meaning.

  The doc string in **chapter_linear-networks/image-classification-dataset.ipynb** says:

```python
def get_dataloader_workers():  #@save
    """Use 4 processes to read the data expect for Windows."""
```

  But I think maybe `except for` will be less ambiguous than `expect for`, especially for those non-native English speakers.

  I am a student learning _d2l_, it is a really amazing book, making deep learning interesting and is friendly to beginners! And I really hope it will become better and better!

Best wishes!

Yours sincerely,
Yijia Shaw

**Comment by astonzhang** [comment]
Good catch! Would you like to send a PR to fix it? See how here: https://d2l.ai/chapter_appendix-tools-for-deep-learning/contributing.html

**Comment by SportsTHU** [comment]
Sure! I have just made a PR, for your reference :)

**Comment by SportsTHU** [comment]
Sure! I have just made a PR, for your reference :)

**Comment by astonzhang** [comment]
Could you point me to your PR?

**Comment by SportsTHU** [comment]
Oh, because I am not that familiar with _Pull Request_. So I just make a PR 2 days ago, but didn't submit it correctly. The PR is https://github.com/d2l-ai/d2l-en/pull/1215
I am sorry for being late.

**Comment by astonzhang** [comment]
Thanks for being a contributor to D2L!
https://github.com/d2l-ai/d2l-en/commit/b767e858885e9ee0125d2680181652371e19629b#diff-12c91c71c89f53d4c79132aefe798e57R426

**Comment by SportsTHU** [comment]
Thank you!
Hope _D2L_ will become better and better, making more people enjoy `Deep Learning`!
