### ISSUE TITLE
FIXME that should be fixed

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-en#1216]
* FIXME, don’t use Sequential to implement MySequential. in http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_deep-learning-computation/model-construction.html

**Comment by terrytangyuan** [comment]
Could you clarify? Currently the implementation of `MySequential` does not use Sequential. 

```
class MySequential(tf.keras.Model):
    def __init__(self, *args):
        super().__init__()
        self.modules = []
        for block in args:
            # Here, `block` is an instance of a `tf.keras.layers.Layer`
            # subclass
            self.modules.append(block)

    def call(self, x):
        for module in self.modules:
            x = module(x)
        return x

```

**Comment by astonzhang** [comment]
It seems that this FIXME is added by Mu. @mli, shall we update this FIXME?

**Comment by terrytangyuan** [comment]
Yes this has been resolved before our announcement of TF implementation. Where did you see the FIXME?

**Comment by astonzhang** [comment]
Just click the link and turn on tf tab, ctrl + F "FIXME".
