### ISSUE TITLE
adaptation inconsistency: wrong output in maxpool

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-en#1270]
http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_convolutional-neural-networks/pooling.html

mxnet

pool2d = nn.MaxPool2D((2, 3), padding=(1, 2), strides=(2, 3))
pool2d(X)
Copy to clipboard
array([[[[ 0.,  3.],
         [ 8., 11.],
         [12., 15.]]]])

pt

pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)
Copy to clipboard
tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

**Comment by merajhashemi** [comment]
pytorch:
`pool2d = nn.MaxPool2d((2, 2), padding=(1, 1),  stride=(2,3))`
