### ISSUE TITLE
Errors in train_ch3

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-en#1272]
http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-1273/5/

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-a66acf440358> in <module>
      1 num_epochs = 10
----> 2 train_ch3(net, train_iter, test_iter, cross_entropy, num_epochs, updater)

<ipython-input-17-69547449c08e> in train_ch3(net, train_iter, test_iter, loss, num_epochs, updater)
      4                         legend=['train loss', 'train acc', 'test acc'])
      5     for epoch in range(num_epochs):
----> 6         train_metrics = train_epoch_ch3(net, train_iter, loss, updater)
      7         test_acc = evaluate_accuracy(net, test_iter)
      8         animator.add(epoch + 1, train_metrics + (test_acc,))

<ipython-input-15-4f3535c36751> in train_epoch_ch3(net, train_iter, loss, updater)
     18         else:
     19             l.sum().backward()
---> 20             updater(X.shape[0])
     21             metric.add(float(l.sum()), accuracy(y_hat, y), y.numel())
     22     # Return training loss and training accuracy

<ipython-input-18-58a28fb63f44> in updater(batch_size)
      2
      3 def updater(batch_size):
----> 4     return d2l.sgd([W, b], lr, batch_size)

~/code/git_repo/d2l-en/d2l/torch.py in sgd(params, states, hyperparams)
   1097 def sgd(params, states, hyperparams):  #@save
   1098     for p in params:
-> 1099         p.data.sub_(hyperparams['lr'] * p.grad)
   1100         p.grad.data.zero_()
   1101

TypeError: 'int' object is not subscriptable
TypeError: 'int' object is not subscriptable

**Comment by astonzhang** [comment]
I've fixed it: https://github.com/d2l-ai/d2l-en/commit/96b6ceafbc72a081f811b781ef4db23e56534a41

**Comment by ButuSun** [comment]
Hello, how should I solve the following error?
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 2
      1 num_epochs = 10
----> 2 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, trainer)

File ~/miniconda3/lib/python3.8/site-packages/d2l/torch.py:318, in train_ch3(net, train_iter, test_iter, loss, num_epochs, updater)
    315 animator = Animator(xlabel='epoch', xlim=[1, num_epochs], ylim=[0.3, 0.9],
    316                     legend=['train loss', 'train acc', 'test acc'])
    317 for epoch in range(num_epochs):
--> 318     train_metrics = train_epoch_ch3(net, train_iter, loss, updater)
    319     test_acc = evaluate_accuracy(net, test_iter)
    320     animator.add(epoch + 1, train_metrics + (test_acc,))

File ~/miniconda3/lib/python3.8/site-packages/d2l/torch.py:259, in train_epoch_ch3(net, train_iter, loss, updater)
    257     l.mean().backward()
    258     updater.step()
--> 259     metric.add(float(l) * len(y), accuracy(y_hat, y),
    260                y.size().numel())
    261 else:
    262     # Using custom built optimizer & loss criterion
    263     l.sum().backward()

ValueError: only one element tensors can be converted to Python scalars
