### ISSUE TITLE
13.7 SSD : context is chaos

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1279]
![image](https://user-images.githubusercontent.com/25657787/88915551-1b694580-d297-11ea-9762-408fea664075.png)
![image](https://user-images.githubusercontent.com/25657787/88915096-3f785700-d296-11ea-8fc0-342eddd4d9cf.png)

http://preview.d2l.ai/d2l-en/master/chapter_computer-vision/ssd.html
Loss Function shouldn't plugs into the exercises. @astonzhang

**Comment by astonzhang** [comment]
This loss is not essential for the main text so keeping it in exercises makes it optional for readers.

**Comment by StevenJokes** [comment]
I haven't find the relation of 1st exercise and this loss, maybe we put the loss at last?

**Comment by astonzhang** [comment]
Would this be clearer?
https://github.com/d2l-ai/d2l-en/commit/211f506ce7ec4952488a3b23d3dc6465064b15c4

**Comment by StevenJokes** [comment]
yes
