### ISSUE TITLE
PR #1282 is failing to pass the ci.

### ISSUE THREAD

**Issue by abhinavsp0730** [d2l-ai/d2l-en#1286]
@astonzhang  @AnirudhDagar @terrytangyuan 

### Issue.
The PR #1282 is failing to pass the ci. You, can find the error [here](http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-1282/7/pipeline/).

### Code to reproduce the error.
https://colab.research.google.com/drive/1zaW6HrrhZD1ntx_W4vxpb8Q0KSbc7mk4?usp=sharing

### Details.
I'm not able to use train_ch6 more than one time in a notebook. While executing the train_ch6 function 2nd time I'm getting error. For executing train_ch6  2nd time I've to execute the cell which is having the network architecture once again.

PS: Please refer to the colab notebook for reproducing the error.

**Comment by terrytangyuan** [comment]
The variable `net` might get referenced/updated inside `train()`. Could you look into it?

**Comment by abhinavsp0730** [comment]
I'm not able to find anyway to run the Train_ch6 more than one.

The only Idea I'm having is to make new variable every time.

But, It'll look ugly. Would you please suggest me a better solution.

**Comment by abhinavsp0730** [comment]
I guess I've to do something like this inside train()
``` 
net = trained_net
 del net
return trained_net
```

**Comment by abhinavsp0730** [comment]
@terrytangyuan  Tried every possible way, but none of them worked. Please have a look again.

**Comment by abhinavsp0730** [comment]
update: The issue has been fixed.
Thanks, @terrytangyuan  for giving me the cause for the error and providing me the correct path to solve it.

closing the issue.
