### ISSUE TITLE
github buttons not working

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1291]
![image](https://user-images.githubusercontent.com/25657787/89412999-9a102800-d75a-11ea-87c8-ff35aafa8566.png)
We need to add spaces to separate two words, when it happens.
http://preview.d2l.ai/d2l-en/master/
http://d2l.ai/

**Comment by AnirudhDagar** [comment]
I don't understand the issue?

**Comment by StevenJokes** [comment]
The issue is that it was button like 
![image](https://user-images.githubusercontent.com/25657787/89433022-63470b80-d774-11ea-9b3a-1b52dd26c208.png)

**Comment by AnirudhDagar** [comment]
So?

**Comment by StevenJokes** [comment]
So the button isn't working. Just look not so pretty.

**Comment by astonzhang** [comment]
Thanks. I think the buttons work now.
