### ISSUE TITLE
add image/

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1293]
@terrytangyuan 
![image](https://user-images.githubusercontent.com/25657787/89419440-f166c600-d763-11ea-8d72-d1008988f66c.png)

**Comment by terrytangyuan** [comment]
What do you mean?

**Comment by AnirudhDagar** [comment]
@StevenJokes this is perfectly ok. Please only open relevant issues.
Thank you!

I'm closing this.

**Comment by StevenJokes** [comment]
@terrytangyuan 
I just suggest add your .jpg to image. It maybe cause problem when producing a pdf file. I'm not sure about it.

**Comment by StevenJokes** [comment]
My concern is unnecessary.  PDF doesn't have any authors'  images
![image](https://user-images.githubusercontent.com/25657787/89437857-ab692c80-d77a-11ea-9cfb-07593d65916e.png)
