### ISSUE TITLE
Blue line doesn't show in my 11.5 code

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1294]
![image](https://user-images.githubusercontent.com/25657787/89433406-dfd9ea00-d774-11ea-9495-81a2787759cc.png)
My code:https://github.com/StevenJokes/d2l-en-read/blob/master/Ch11_Optimization_Algorithms/11-5.ipynb
@AnirudhDagar

**Comment by AnirudhDagar** [comment]
Works for us. Try running in collab. Did you change anything? Your loss seems to be `0.718` and we fixed our `ylim` to `[0.22,0.35]`. Hence no plot for you.

**Comment by StevenJokes** [comment]
I hate you just close the issue. I don't change anything. You can check my code here: https://github.com/StevenJokes/d2l-en-read/blob/master/Ch11_Optimization_Algorithms/11-5.ipynb

**Comment by AnirudhDagar** [comment]
If you want you can reopen the issue. I closed it since there was no problem when I ran it. Also please use only the latest binaries.
