### ISSUE TITLE
Adding code in tensorflow and pytorch 

### ISSUE THREAD

**Issue by ankishb** [d2l-ai/d2l-en#1296]
First of all, Thanks for sharing this amazing book!

I would love to contribute in the form of code base in the tensorflow and pytorch. Please let me know if this option is open?

**Comment by StevenJokes** [comment]
Yes, http://preview.d2l.ai/d2l-en/master/chapter_appendix-tools-for-deep-learning/contributing.html

**Comment by ankishb** [comment]
Thanks, got it.

**Comment by StevenJokes** [comment]
If you use Win10, you should pay attention to https://github.com/d2l-ai/d2l-en/pull/1231.

**Comment by StevenJokes** [comment]
@ankishb ,I'm closing the issue.

**Comment by ankishb** [comment]
Sure, closing it.
