### ISSUE TITLE
[pytorch] code for 17.1: GAN

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1300]
I'm trying to translate [GAN](http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/gan.html) to pytorch.

When I search, then I found someone has translated it in https://www.pythonf.cn/read/33854.
But I have some questions about the Sigmoid layer.

![image](https://user-images.githubusercontent.com/25657787/89544619-f0519980-d834-11ea-8cbe-0cbac639d12f.png)

http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/gan.html

I have tried to read https://mxnet.incubator.apache.org/versions/1.6/api/python/docs/api/gluon/nn/index.html#mxnet.gluon.nn.Activation.

There is no source code. What is the default Activation? Do I need to add the Sigmoid layer?

**Comment by StevenJokes** [comment]
lr_D, lr_G, latent_dim, num_epochs = 0.05, 0.005, 2, 20
train(net_D, net_G, data_iter, num_epochs, lr_D, lr_G,
      latent_dim, data[:100].numpy())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
 in 
      1 lr_D, lr_G, latent_dim, num_epochs = 0.05, 0.005, 2, 20
----> 2 train(net_D, net_G, data_iter, num_epochs, lr_D, lr_G,
      3       latent_dim, data[:100].numpy())

 in train(net_D, net_G, data_iter, num_epochs, lr_D, lr_G, latent_dim, data)
     19             batch_size = X.shape[0]
     20             Z = torch.normal(0, 1, size=(batch_size, latent_dim))
---> 21             metric.add(update_D(X, Z, net_D, net_G, loss, trainer_D),
     22                        update_G(Z, net_D, net_G, loss, trainer_G),
     23                        batch_size)

 in update_D(X, Z, net_D, net_G, loss, trainer_D)
     11     # computing gradients.
     12     fake_Y = net_D(fake_X.detach())
---> 13     loss_D = (loss(real_Y, ones) + loss(fake_Y, zeros)) / 2
     14     loss_D.backward()
     15     trainer_D.step(batch_size)

~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
    514 
    515     def forward(self, input, target):
--> 516         return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
    517 
    518 

~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py in binary_cross_entropy(input, target, weight, size_average, reduce, reduction)
   2376         weight = weight.expand(new_size)
   2377 
-> 2378     return torch._C._nn.binary_cross_entropy(
   2379         input, target, weight, reduction_enum)
   2380 

RuntimeError: all elements of input should be between 0 and 1

---

Now I know the Sigmoid is necessary.

**Comment by StevenJokes** [comment]
@AnirudhDagar ,Would you like to help me to review my pytorch code before I PR to GAN.md ? It cost me whole night.
https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/my5gan.ipynb

**Comment by StevenJokes** [comment]
Any reply? :face_with_raised_eyebrow:
@goldpiggy

I really need a job . 
@mli  @astonzhang @terrytangyuan 
这几天一直失眠 :crying_cat_face:感觉毕业即失业太痛苦了

山西大学金融本科, 简历；https://blog.dltech.xyz/post/jian-li/
Github: https://github.com/StevenJokes
精读D2L的repo：https://github.com/StevenJokes/d2l-en-read

计算机基础也就凑合，啊，真的在家待疯了，
话说能不能不面试，真的 :joy:好菜啊 :persevere:
带带我带带我，邮箱：llgg8679@qq.com
最近学校下周三调档案，之后就不能轻易转工作档案了。 :mask:
如果再没工作，没钱的我 :sob:就只能奋力二战考研了，那我就不能论坛、PR和issue了。

---

这里我把GAN的mxnet换成pytorch了：
https://github.com/d2l-ai/d2l-en/issues/1300里提到的
https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/my5gan.ipynb

**Comment by AnirudhDagar** [comment]
@StevenJokes I can't review your code like this. Please follow the contribution guidelines to make the PR similar to how other PRs have been made. We can review then.

**Comment by StevenJokes** [comment]
Ok, I'm trying

**Comment by StevenJokes** [comment]
Any reply? :face_with_raised_eyebrow:
@goldpiggy

I really need a job . 
@mli  @astonzhang @terrytangyuan 
这几天一直失眠 :crying_cat_face:感觉毕业即失业太痛苦了

山西大学金融本科, 简历；https://blog.dltech.xyz/post/jian-li/
Github: https://github.com/StevenJokes
精读D2L的repo：https://github.com/StevenJokes/d2l-en-read

计算机基础也就凑合，啊，真的在家待疯了，
话说能不能不面试，真的 :joy:好菜啊 :persevere:
带带我带带我，邮箱：llgg8679@qq.com;微信：C867907127;
最近学校下周三调档案，之后就不能轻易转工作档案了。 :mask:
如果再没工作，没钱的我 :sob:就只能奋力二战考研了，那我就不能论坛、PR和issue了。

---

这里我把GAN的mxnet换成pytorch了：
https://github.com/d2l-ai/d2l-en/issues/1300里提到的
https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/my5gan.ipynb

所有的研究过程：
https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/gan_torch.ipynb
