### ISSUE TITLE
we should use solid line ：3*3

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1303]
![image](https://user-images.githubusercontent.com/25657787/89662333-8275a280-d906-11ea-838b-47384060c68c.png)
![image](https://user-images.githubusercontent.com/25657787/89662515-c8cb0180-d906-11ea-8626-19381c7378d7.png)

**Comment by StevenJokes** [comment]
@goldmermaid

**Comment by astonzhang** [comment]
fixed: https://github.com/d2l-ai/d2l-en/commit/480040486e8d2a8612aa0079d2278d7f4db921f7
