### ISSUE TITLE
 encoding='utf-8' , is necessary to avoid `d2lbook build lib`:UnicodeDecodeError

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1320]
win10:
![image](https://user-images.githubusercontent.com/25657787/89751104-5d00b880-db01-11ea-8f2b-585239ca661e.png)

**Comment by StevenJokes** [comment]
add `encoding = 'UTF-8'`
![image](https://user-images.githubusercontent.com/25657787/89751653-989c8200-db03-11ea-8c02-9ea7b4f4cc25.png)

**Comment by StevenJokes** [comment]
Problem:
![image](https://user-images.githubusercontent.com/25657787/89751872-7fe09c00-db04-11ea-89a3-8bf260655312.png)
Fix:
![image](https://user-images.githubusercontent.com/25657787/89751886-8f5fe500-db04-11ea-9656-efe29b13a9c0.png)

---

Problem:
![image](https://user-images.githubusercontent.com/25657787/89751898-971f8980-db04-11ea-970e-9810dea21dbc.png)

Fix:
![image](https://user-images.githubusercontent.com/25657787/89751908-a999c300-db04-11ea-8618-67f5db0947d8.png)

Succeed!
![image](https://user-images.githubusercontent.com/25657787/89751914-b3232b00-db04-11ea-8cc3-d666f7b4c4cd.png)

**Comment by StevenJokes** [comment]
Maybe I should PR in d2lbook?

**Comment by abhinavsp0730** [comment]
Feel free to send a PR for windows support for d2lbook. Otherwise, you can just follow the steps which I've mention here, https://github.com/d2l-ai/d2l-en/issues/1323#issuecomment-671242243

**Comment by StevenJokes** [comment]
Still have problem in #1321
