### ISSUE TITLE
Please help me `d2lbook build lib` in linux/macOS

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1323]
@AnirudhDagar , I haven't figure out how to `d2lbook build lib` in my WIN10. 
Not solve: https://github.com/d2l-ai/d2l-en/issues/1321
solve:https://github.com/d2l-ai/d2l-en/issues/1320
I have gan.md in my repo: https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/gan%20-%20Copy.md
You just need to move it to the right folder and rename it  to gan.md.
And as you say, `d2lbook build lib`  and PR for me. Thanks a lot advancely.

**Comment by AnirudhDagar** [comment]
@abhinavsp0730 PTAL

**Comment by abhinavsp0730** [comment]
d2lbook is not fully supported in windows. It's only supported in Linux/Mac os. But you  can  download ubuntu app from Microsoft store and then after installing it you can run ubuntu in Windows. 

After installing ubuntu app from Microsoft store you need to do simply this things:
1. Install Python 3
2. If you wish install Venv
3. Make a virtual env .(or ignore this step)
3. Install d2lbook
4. Then go to the root folder, where you're having  the forked files from d2l repo.
5. Then just do, ```d2lbook build lib``` .

**Comment by StevenJokes** [comment]
I know you are talking about WSL. I used it for a while. It is not so convenient to use anaconda in WSL as I know. 
And it maybe has some problem with virtualbox I am using for docker now. 
https://stackoverflow.com/questions/62184881/virtualbox-and-wsl2.
So I feel it is not so worth to waste a lot of time to install it and config VPN for GFW.
@AnirudhDagar Please help me to PR. You can feel free. And it's better for you to ask mli to offer me a job.

**Comment by abhinavsp0730** [comment]
Well this is a just quick fix. You can do whatever you want in windows, but when you need to execute ``` d2lbook build lib```  you can execute in WSL. Rest of the things we're gonna do in Windows. This is just a quick fix untill there is a windows support of d2lbook.

**Comment by StevenJokes** [comment]
Yes, I don't have time to install WSL and config for a project I will not PR any more.. My family always blame me "playing computer". So if I don't get some money, maybe I have to read some boring books to prepare for my exam next months just to get a CS master degree. I heard the message that having a CS degree is so necessary to get a job to big company like FLAG, and I only have a finance undergraduate degree now.

**Comment by StevenJokes** [comment]
https://github.com/StevenJokes/d2l-en-read/blob/master/chapter-generative-adversarial-networks/PR1308.ipynb

**Comment by StevenJokes** [comment]
switch 'discriminator', 'generator' for #1326

**Comment by StevenJokes** [comment]
@goldmermaid maybe you can help me to update gan.md for pytorch.

**Comment by goldmermaid** [comment]
Hi @StevenJokes , could you reopen a PR for https://github.com/d2l-ai/d2l-en/pull/1327#? (And please don't link non-necessary PR/issues together.)

**Comment by StevenJokes** [comment]
@goldmermaid. #1327 is right?[reopen it already.] (VS #1335 is wrong?)
#1323 is related to #1326. The gan.md include the code for gan. 
So if #1327 is right, maybe my gan.md (include mxnet and pytorch code) should change again, just because I use the #1335 code.
Just to ask you to confirm it.

**Comment by StevenJokes** [comment]
@AnirudhDagar Please help me. Add GAN for me.
😢
