### ISSUE TITLE
Colab does not support MXNet 1.6 

### ISSUE THREAD

**Issue by mathresearch** [d2l-ai/d2l-en#1324]
ERROR: Could not find a version that satisfies the requirement mxnet-cu101mkl==1.6.0 (from versions: 1.4.1, 1.5.0, 1.5.1, 1.5.1.post0, 1.6.0.post0)
ERROR: No matching distribution found for mxnet-cu101mkl==1.6.0

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/89906134-93335a80-dc1d-11ea-9ca0-032218fc9786.png)
you are right!
@astonzhang

**Comment by StevenJokes** [comment]
`!pip install -U mxnet-cu101mkl==1.6.0.post0 # updating mxnet to at least v1.6`
use it to replace `!pip install -U mxnet-cu101mkl==1.6.0 # updating mxnet to at least v1.6`

**Comment by StevenJokes** [comment]
@astonzhang we should change all ipynb ASAP.

**Comment by astonzhang** [comment]
Thanks for reporting this issue. It's due to the update from MXNet and now it's fixed.
