### ISSUE TITLE
add how many seconds cost for all training

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1330]
![image](https://user-images.githubusercontent.com/25657787/89927672-41003280-dc39-11ea-8252-30103d97994e.png)

**Comment by StevenJokes** [comment]
`f', totally {timer.stop().3f} secs'`

**Comment by StevenJokes** [comment]
Does time.stop() mean that only first epoch time?

**Comment by goldmermaid** [comment]
Hi @StevenJokes , please distinguish "Issue" and "question". If you find an issue of the existing text, formula or code that **everyone** questioned about, please ask here. On the other hand, please ask it in the discussion forum.

Please close this issue if it is clear to you. Thanks!

**Comment by StevenJokes** [comment]
I'm suggesting a feature for all trainings here, not only this training.
How to calculate total epochs time? 
I maybe get a hint from the notebook's GPU time to get if my cpu has enough ability to finish training code in 5min.
I'll avoid wasting unnessary waiting time.

**Comment by astonzhang** [comment]
Users can freely print out the actual running time. For consistency throughout the book, we think throughput is a better measure for different types of tasks.
