### ISSUE TITLE
require #@save after def and class

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1337]
![image](https://user-images.githubusercontent.com/25657787/90001435-0394b700-dcc4-11ea-91f2-faaa6cf5f9f0.png)
I found #@save until
![image](https://user-images.githubusercontent.com/25657787/90001705-58d0c880-dcc4-11ea-976f-3f85bdfbbe45.png)

**Comment by StevenJokes** [comment]
Maybe we should keep all #@save just after two spaces.

**Comment by astonzhang** [comment]
It's only for those that are saved to the d2l package.
