### ISSUE TITLE
Random labels on retrieving data with shuffle = false

### ISSUE THREAD

**Issue by aksrajvanshi** [d2l-ai/d2l-en#1341]
Hey! I am trying to run Section 13.6 with the banana dataset. I have turned the shuffle= False with getting the training dataset. However, I tried printing the first 10 images along with the labels. The labels turn out to be different every time. 

![Screen Shot 2020-08-12 at 8 03 08 PM](https://user-images.githubusercontent.com/16722550/90080003-7f4c2f00-dcd7-11ea-91a3-969b304934e1.png)

![Screen Shot 2020-08-12 at 8 04 28 PM](https://user-images.githubusercontent.com/16722550/90080008-82471f80-dcd7-11ea-9121-b3c5905f9af1.png)

Let me know if I can get the labels in the right and unrandomized order in some way ?

**Comment by astonzhang** [comment]
@xiaotinghe, can you take a look at it first?

**Comment by xiaotinghe** [comment]
These differences are caused by random clipping. When loading data, we use random clipping by `rand_ crop=1`.
If you want to get the raw data, you can turned the `rand_ crop=0`.

**Comment by aksrajvanshi** [comment]
Great! that works. Thank you! :)
