### ISSUE TITLE
[TF] Bug in RNN Scratch TensorFlow implementation

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#1349]
Perplexity is too high and the model doesn't converge. [Here](http://preview.d2l.ai/d2l-en/PR-1348/chapter_recurrent-neural-networks/rnn-scratch.html)

Please use this thread to track the issues with the RNN TF implementation @abhinavsp0730 @terrytangyuan

**Comment by terrytangyuan** [comment]
@abhinavsp0730 Any progress on this yet?

**Comment by abhinavsp0730** [comment]
Sorry for the delayed response. 
https://github.com/d2l-ai/d2l-en/pull/1450 I've done some modification but still, the model is not converging. @terrytangyuan It'd be great if you take a closer look and help me out.

**Comment by charleybeller** [comment]
The current implementation converges quickly (perplexity around 17-18) and always predicts space (argmax(y) = 1). Not sure what's going wrong.

**Comment by astonzhang** [comment]
Fixed at https://github.com/d2l-ai/d2l-en/pull/1552
