### ISSUE TITLE
Unable to read notebook

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1353]
I think we don’t tell them to install jupyter at all.
https://discuss.d2l.ai/t/installation/24/6
new commit: https://github.com/d2l-ai/d2l-en/pull/1304/commits/198cc5ff657ae15c9c510448ffa73ac8bc19e452

**Comment by astonzhang** [comment]
Thanks. It's automatically installed when `d2l` is installed: https://github.com/d2l-ai/d2l-en/blob/master/setup.py#L5
Installing `d2l` is required in the installation section.
