### ISSUE TITLE
How to create a discussion about the book’s chapter？

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1354]
Can you tell me [How to create a discussion about the book’s chapter](https://discuss.d2l.ai/t/how-to-create-a-discussion-about-the-books-chapter/552/3)?
Then I can help you create following discussions for pytorch and tensorflow tab.

**Comment by goldmermaid** [comment]
There is an interesting idea. @astonzhang how do you like this idea?

**Comment by StevenJokes** [comment]
I found if there isn't a matching discussion, the forum will be chaos.

**Comment by astonzhang** [comment]
So far pytorch and tf adaptations are still under development. We will only add discussion threads for them when we feel it's ready. Maybe we will add those discussion threads before next release
