### ISSUE TITLE
Question: TensorFlow/Pytorch code example in pdf version?

### ISSUE THREAD

**Issue by tallamjr** [d2l-ai/d2l-en#1359]
Hello, firstly I would like say thank you for this incredible resource.

My question relates to the downloadable version of the book found at d2l.ai at this link:
https://d2l.ai/d2l-en.pdf

It seems that all the code examples in the PDF are for `mxnet` implementations. Is it possible to
render a PDF version with either Pytorch or TensorFlow examples instead? 

I understand that not all sections have TensorFlow implementations yet
(https://github.com/d2l-ai/d2l-en/issues/1143), but thought I would check to see if this is possible
and perhaps I am just missing something.

**Comment by AnirudhDagar** [comment]
Hi @tallamjr!
At the moment, only MXNET version of the pdf is available.

But we'll add other framework pdf versions soon! Stay tuned.

**Comment by StevenJokes** [comment]
I don't think it is soon... Just wait or join together.
