### ISSUE TITLE
Bug in 16.9: Factorization machines?

### ISSUE THREAD

**Issue by srcomm65** [d2l-ai/d2l-en#1360]
In the model definition in cell 3, the forward methods outputs a sigmoid value.  

If so, the loss should be setup as gluon.loss.SigmoidBinaryCrossEntropyLoss(**from_sigmoid=True**) as per man page (https://mxnet.apache.org/versions/1.6/api/python/docs/api/gluon/loss/index.html#mxnet.gluon.loss.SigmoidBCELoss).   In current implementation, from_sigmoid=False by default

I find that the traning loss converges to near 0, when from_sigmoid=True

![Screen Shot 2020-08-15 at 4 41 40 PM](https://user-images.githubusercontent.com/69734020/90321420-5dd98600-df17-11ea-89f9-36c5ab778808.png)

**Comment by astonzhang** [comment]
@cheungdaven Can you take a look?

**Comment by cheungdaven** [comment]
Thank you for pointing out. Setting it to False will lead to a recalculation of the sigmoid function. Another solution is to remove the sigmoid function in the forward function and keep the from_sigmoid as default.

**Comment by srcomm65** [comment]
@cheungdaven Got it. Two more issues noted

- The accuracy in train function `d2l.train_ch13()` is between the prediction and labels using equality.  Since the prediction in this model is the sigmoid value, the accuracy metric is incorrect.

- Not sure if you really need the linear layer for the first order terms. The embedding reflects the weight, as all features are one-hot.

**Comment by cheungdaven** [comment]
@srcomm65 
As I recall, the evaluation method did force type conversion such that the sigmoid value is transformed into a binary int value. So the evaluation should be correct.  The current accuracy looks lower than the previous version, I am not quite sure what is going on there. It used to be like 80-90 %.


def accuracy(y_hat, y):  #@save
    """Compute the number of correct predictions."""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = d2l.argmax(y_hat, axis=1)        
    cmp = d2l.astype(y_hat, y.dtype) == y
    return float(d2l.reduce_sum(d2l.astype(cmp, y.dtype)))


As for the linear layer, it is consistent with the original FMs,  FMs is an extension of Linear/logistic regression so linear layer is needed.
