### ISSUE TITLE
``d2lbook` package <http://book.d2l.ai/user/markdown.html>`__ 

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1365]
![image](https://user-images.githubusercontent.com/25657787/90339224-0aa02a00-e022-11ea-9d3f-a384f7a83b6e.png)
http://preview.d2l.ai/d2l-en/master/chapter_appendix-tools-for-deep-learning/contributing.html
![image](https://user-images.githubusercontent.com/25657787/90339229-12f86500-e022-11ea-800b-36201a4fa666.png)

**Comment by astonzhang** [comment]
Thanks. I think it's fixed now: http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/d2l-en.pdf
