### ISSUE TITLE
How can I contribute to the Pytorch version release

### ISSUE THREAD

**Issue by wmn7** [d2l-ai/d2l-en#1373]
Hi, if I find some problems in the Pytorch version (in the newest release), but how to edit these.

Like in https://d2l.ai/chapter_preliminaries/linear-algebra.html#matrix-vector-products, 

![snipaste_20200817_171632](https://user-images.githubusercontent.com/21176109/90412415-5e0b8a00-e0ad-11ea-9c77-da805440aab4.jpg)

It should be `torch.mv` rather than `np.dot` here.

**Comment by StevenJokes** [comment]
read http://preview.d2l.ai/d2l-en/master/chapter_appendix-tools-for-deep-learning/contributing.html
look forward to your pr.

**Comment by StevenJokes** [comment]
Can you close now?
