### ISSUE TITLE
Why I can't find the newest def in torch.py

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1374]
@suvaansh @AnirudhDagar 
I'm reviewing https://github.com/d2l-ai/d2l-en/pull/1370/files#
![image](https://user-images.githubusercontent.com/25657787/90412670-f7ec2a80-e0df-11ea-88ee-d4c60bbbcc36.png)

```py
def bbox_to_rect(bbox, color):
    """Convert bounding box to matplotlib format."""
    # Convert the bounding box (top-left x, top-left y, bottom-right x,
    # bottom-right y) format to matplotlib format: ((upper-left x,
    # upper-left y), width, height)
    return d2l.plt.Rectangle(
        xy=(bbox[0], bbox[1]), width=bbox[2]-bbox[0], height=bbox[3]-bbox[1],
        fill=False, edgecolor=color, linewidth=2)
```

I can't find it in my package.
I have try to uninstall and install again.
![image](https://user-images.githubusercontent.com/25657787/90412569-dbe88900-e0df-11ea-81ee-a741a5aa8883.png)

There still is no this function. How to fix it?

**Comment by StevenJokes** [comment]
Maybe @astonzhang needs to upload `d2l` to pypi?

**Comment by StevenJokes** [comment]
Does that means that we should update version everytime when we change `d2l`?
This time is 0.14.3 to 0.14.4.

**Comment by astonzhang** [comment]
I've used a clean machine and followed the installation at http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_installation/index.html . In the end, there is no problem of running `from d2l import mxnet as d2l`. Please make sure that those installation steps are followed strictly, such as running `conda install pip -y`

**Comment by StevenJokes** [comment]
I'm talking about testing pytorch version: https://github.com/d2l-ai/d2l-en/pull/1370
![image](https://user-images.githubusercontent.com/25657787/90766862-cdd47b80-e31e-11ea-85e6-238c9bca468f.png)


And you need to reopen the pull: https://github.com/d2l-ai/d2l-en/pull/1384
![image](https://user-images.githubusercontent.com/25657787/90766805-b9907e80-e31e-11ea-924d-1ebebcdc8ccb.png)

**Comment by StevenJokes** [comment]
Will https://github.com/d2l-ai/d2l-en/pull/1396 fix my problem?
Or you have to upload pip package manually?
@astonzhang

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/91055359-21183800-e657-11ea-853c-29e4528b2f89.png)

![image](https://user-images.githubusercontent.com/25657787/91055332-152c7600-e657-11ea-89f5-ae6ea14b756f.png)

**Comment by StevenJokes** [comment]
@astonzhang 
@astonzhang 
@astonzhang 
But I can't install the newest pypi package `d2l`
Where can I install it?

Or we need to release `d2l` now.

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/91513449-f3f9ad00-e916-11ea-8290-cce257805723.png)

**Comment by astonzhang** [comment]
> @astonzhang
> @astonzhang
> @astonzhang
> But I can't install the newest pypi package `d2l`
> Where can I install it?
> 
> Or we need to release `d2l` now.

You mean you want to pip install the latest `d2l` on the master (development) branch? You may:
git+https://github.com/d2l-ai/d2l-book

**Comment by astonzhang** [comment]
Note that master branch is for *developers* only. We upload the updated version of d2l package only when the master branch is pushed to the release branch. The release branch is for end users.

**Comment by StevenJokes** [comment]
I'm still not a developer??? 😢 😢 😢  After so many PR and issue?
![image](https://user-images.githubusercontent.com/25657787/91517431-52775900-e920-11ea-9b14-e76c6d04a027.png)


![image](https://user-images.githubusercontent.com/25657787/91517473-6d49cd80-e920-11ea-9311-ff0e07cac8e1.png)
`pip install git+https://github.com/d2l-ai/d2l-book` is only the `d2lbook` package, not `d2l`

**Comment by StevenJokes** [comment]
Is there some way to publish the nightly version of pypi package?
@astonzhang 
Or for me, install the github `d2l` package?

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/91517983-b51d2480-e921-11ea-9403-abba14e4faf2.png)
And I spent so many time on discussion. I'm not a developer???

I have tried `pip install d2l --pre -i https://pypi.python.org/simple`
It didn't work.
At least, you need to offer --pre to users.

**Comment by StevenJokes** [comment]
Or I can download github repo, then replace `d2l` in
![image](https://user-images.githubusercontent.com/25657787/91518996-029a9100-e924-11ea-82e5-87e78cca6849.png)

**Comment by StevenJokes** [comment]
`pip install git+https://github.com/d2l-ai/d2l-en`
OK now.
You told me the right way but wrong repo.:cry
@astonzhang
