### ISSUE TITLE
No content and structure for last chapters

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1376]
![image](https://user-images.githubusercontent.com/25657787/90420135-23741280-e0ea-11ea-8efa-482a4eb22966.png)

**Comment by goldmermaid** [comment]
Hey @StevenJokes , thanks for raising this issue. For the current cycle of revision, we are focusing on the first 15 chapters. While we will add more contents to the final ones later. Please close the issue if no other doubt. ;)

**Comment by StevenJokes** [comment]
OK. just be quick. Maybe I can help you?
