### ISSUE TITLE
Can you tell me these packages' function?

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1378]
PS C:\Users\a8679> pip search d2l
d2l (0.14.3)      - Dive into Deep Learning
  INSTALLED: 0.14.3 (latest)
d2l-zh (0.8.10)   - Dive into Deep Learning (in Chinese) Utils
quizmake (0.1.1)  - Question generator package for D2L and Moodle
d2lmf (1.0.0)     - A command-line tool to help mark assignments submitted to D2L.

**Comment by goldmermaid** [comment]
Hey @StevenJokes  great questions and answers! ;) I suggest you to ask the similar questions on the forum since the question will valuable to other readers. Please close the issue if there is no other doubt.

**Comment by StevenJokes** [comment]
OK. https://discuss.d2l.ai/t/can-you-tell-me-these-packages-function/731
