### ISSUE TITLE
8.5.3 RNN Model missing link

### ISSUE THREAD

**Issue by HarryDC** [d2l-ai/d2l-en#1379]
in the second paragraph of https://d2l.ai/chapter_recurrent-neural-networks/rnn-scratch.html#rnn-model it says 

"As described in :numref:sec_mlp ..."

**Comment by astonzhang** [comment]
Thanks. It's fixed in the preview version: http://preview.d2l.ai/d2l-en/master/chapter_recurrent-neural-networks/rnn-scratch.html#rnn-model
It will show up on the main site when we make a new release soon.
