### ISSUE TITLE
Bug in the cross entropy implementation for Tensorflow in Section 18.11.5.1

### ISSUE THREAD

**Issue by kusur** [d2l-ai/d2l-en#1382]
@astonzhang , @AnirudhDagar , @terrytangyuan 

While going through the code of cross entropy in Tensorflow, I found that the output of tensorflow's implementation was significantly different from mxnet and pytorch. After taking a look at it, it seems that the logic for calculation of cross entropy in tensorflow is flawed. It should be the following - 

```python
def cross_entropy(y_hat, y):
    ce = -tf.math.log(y_hat[range(len(y)), y])
    return tf.reduce_mean(ce)
```
instead of 
```python
def cross_entropy(y_hat, y):
    ce = -tf.math.log(y_hat[:, :len(y)])
    return tf.reduce_mean(ce)
```

Could someone please make these changes in the code? Thanks

**Comment by terrytangyuan** [comment]
@kusur The suggested change is not valid TF syntax. See logs [here](http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-1437/1/pipeline). I'll take a closer look soon but let me know if you have any suggested fix in the meantime.

**Comment by biswajitsahoo1111** [comment]
It's fixed in [1769](https://github.com/d2l-ai/d2l-en/pull/1769).
