### ISSUE TITLE
I will help you to create more new topic in discuss.d2l.ai

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1385]
I think 
https://discuss.d2l.ai/t/information-theory-potential-issue-with-part-3-of-3rd-exercise-in-the-section-18-11-7/721/2
reflect a problem that we don't have matching discussion for remaining chapters.

@astonzhang Can you tell me [How to create a discussion about the book’s chapter?](https://discuss.d2l.ai/t/how-to-create-a-discussion-about-the-books-chapter/552)

Just need to add the matching chapters' URL and PR the matching discussions' URL in github?

**Comment by StevenJokes** [comment]
One more thing, do we need an extra discussion for three frameworks?
Sometimes just contrast about three frameworks and talk about chapters' math and DL history.

**Comment by goldmermaid** [comment]
Hi @StevenJokes , I am not fully understand what do you mean for "matching discussion". Could you elaborate more? Thanks!

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/90860069-f068a200-e3bb-11ea-8c67-f5c12f6fc299.png)

**Comment by StevenJokes** [comment]
One more thing, do we need an **extra discussion** for three frameworks?
Sometimes just contrast about three frameworks and talk about chapters' math and DL history.

**Comment by StevenJokes** [comment]
My commit:
https://github.com/d2l-ai/d2l-en/pull/1358/commits/f37b08a3493158a23c9525d8d70fd3bddcf9ab10
My discuss:
https://discuss.d2l.ai/t/generative-adversarial-networks/776/2

@astonzhang 
Am I right?
