### ISSUE TITLE
Neural Collaborative Filtering for Personalized Ranking Prediction Layer missing?

### ISSUE THREAD

**Issue by LeeJZh** [d2l-ai/d2l-en#1399]
> To fuse the results of GMF and MLP, instead of simple addition, NeuMF concatenates the second last layers of two subnetworks to create a feature vector which can be passed to the further layers. Afterwards, the ouputs are projected with matrix  h  and a sigmoid activation function. 

However the code is 

> con_res = np.concatenate([gmf, mlp], axis=1)
> return np.sum(con_res, axis=-1)

Should not np.sum be replaced with a dense layer?

**Comment by astonzhang** [comment]
@cheungdaven

**Comment by cheungdaven** [comment]
@LeeJZh You're right, we can add a dense layer over it. They will show similar performances.
@astonzhang I think we can merge this request.

**Comment by astonzhang** [comment]
Thanks. It's merged.
