### ISSUE TITLE
8.6 RuntimeError: Can't detach views in-place. Use detach() instead

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1409]
![image](https://user-images.githubusercontent.com/25657787/91520982-42b04280-e929-11ea-8a2c-bf15aa7e1658.png)

**Comment by AnirudhDagar** [comment]
It seems you are not running from the master. Please use the code from the master branch of repo to run chapters which are yet to be released. Or wait for the release if you want the wheel builds.

Sections after Ch7 are yet to be announced officially. Thanks :)

**Comment by StevenJokes** [comment]
I'm running from the master.
I have run `pip install git+https://github.com/d2l-ai/d2l-en`
@AnirudhDagar

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/91524488-f4537180-e931-11ea-9c84-929034419032.png)
It is the newest.

**Comment by AnirudhDagar** [comment]
In that case please double-check your code. As I said, I just ran Section 8.6 and it works just fine for me.

**Comment by StevenJokes** [comment]
Your version of pytorch?
![image](https://user-images.githubusercontent.com/25657787/91524878-ea7e3e00-e932-11ea-9249-ba8ad3f17374.png)

**Comment by StevenJokes** [comment]
I'm using cpu version BTW

**Comment by AnirudhDagar** [comment]
We recommend using the latest version i.e 1.6 and we test all the code against the latest version. both on CPU and GPU.
Thanks!

**Comment by StevenJokes** [comment]
Oh my god.
I found the reason.
`activate pytorch` didn't work in Powershell, only in cmd or git bash.
I hate WIN10. I need money to buy a new computer.
So `pip install git+https://github.com/d2l-ai/d2l-en` didn't install in the right place.

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/91525997-44800300-e935-11ea-9a6d-aa94a0cea41a.png)
Working now!
