### ISSUE TITLE
Bug in Chapter 8

### ISSUE THREAD

**Issue by Okroshiashvili** [d2l-ai/d2l-en#1416]
In **8.5. Implementation of Recurrent Neural Networks from Scratch** there is a bug in **train_epoch_ch8** function. It gives **AttributeError: module 'd2l.torch' has no attribute 'size'**. I did not figure out why is this case. Please, have a look.

**Comment by astonzhang** [comment]
Are you using the latest version? pip install d2l --upgrade

**Comment by Okroshiashvili** [comment]
The upgrading package solved the problem. Closing the issue.
