### ISSUE TITLE
[mxnet]MXNetError: [13:10:18] src/engine/threaded_engine.cc:333: Check failed: exec_ctx.dev_id < device_count_ (1 vs. 1) 

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1430]
![image](https://user-images.githubusercontent.com/25657787/92326734-ce8f4080-f086-11ea-9ed2-7c16d755334c.png)
https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_computational-performance/multiple-gpus.ipynb#scrollTo=qmjTcAuRh9h4

**Comment by astonzhang** [comment]
This section requires multiple GPUs to run, while colab notebook has 1 GPU
