### ISSUE TITLE
Need to fix ax.imshow(d2l.numpy(img)) in torch.py

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1431]
![image](https://user-images.githubusercontent.com/25657787/92329427-f6d46a80-f099-11ea-9637-232aa072e458.png)
https://github.com/StevenJokes/d2l-en-read/blob/master/Ch13_CV/13_2pt_colab_(3).ipynb

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/92329470-3307cb00-f09a-11ea-91b5-dd82c7a21a62.png)
It works.

**Comment by astonzhang** [comment]
I cannot reproduce the error in the notebook.
