### ISSUE TITLE
Some :numref:`some_label` show-up in the pdf and website

### ISSUE THREAD

**Issue by phupe** [d2l-ai/d2l-en#1448]
Fyi, for both the pdf file (https://d2l.ai/d2l-en.pdf) and the website, some internal link that refer to either Fig or Sections do not show-up:

![numref-broken-link](https://user-images.githubusercontent.com/38132572/93350867-5b7d8b00-f839-11ea-841e-b0a5e3deb341.png)

**Comment by Vijayabhaskar96** [comment]
I see lot of :eqref:eq_matrix_def in [this chapter](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

**Comment by astonzhang** [comment]
Thanks for reporting. This is a known issue due to our building tool. We will fix it but it is currently not among our prioritized items.
