### ISSUE TITLE
why `get_dataloader_workers()` are different in mxnet.py and torch.py?

### ISSUE THREAD

**Issue by StevenJokess** [d2l-ai/d2l-en#1455]
torch.py:
![image](https://user-images.githubusercontent.com/71307974/93661752-e30f0800-fa8c-11ea-8727-2e5c7e9a732c.png)
mxnet.py:
![image](https://user-images.githubusercontent.com/71307974/93661758-ebffd980-fa8c-11ea-82f0-a8ff6e4125c7.png)

**Comment by astonzhang** [comment]
MXNet will support this for windows later. 
In the future, please post questions on the forum. This is for reporting issues.

**Comment by StevenJokess** [comment]
forum's question never get attention...
cheer up, new MXNet!
