### ISSUE TITLE
Possible U-Net subsection in Chapter 7? 

### ISSUE THREAD

**Issue by gregbruss** [d2l-ai/d2l-en#1460]
Hi! Looking for a PR opportunity, I'm wondering if adding a subsection on [U-Net](https://arxiv.org/abs/1505.04597) might be a worthwhile contribution to Chapter 7: Modern ConvNets. 

Just in terms of pedagogy, it might work to have it right before the NiN subchapter. Happy to send a PR if people think it would be worthwhile, I'm interested to hear what the community thinks and if a U-Net subsection makes sense / would fit in, to that chapter.

Cheers.

**Comment by astonzhang** [comment]
Thanks for the interest! Our current goal is to finalize the entire book with v1.0 release asap so we intend not to add new sections before v1.0. Even for expanding chap 7 after v1.0, we may prioritize more recent architectures such as SENet, MobileNets, etc. However, you are welcome to contribute a PR of U-Net to contrib/ . It may get revised and moved back to main text when there's a good fit.
