### ISSUE TITLE
[WIP] New chapters: ML in practice, AutoML 

### ISSUE THREAD

**Issue by jwmueller** [d2l-ai/d2l-en#1476]
Plan is to contribute two new chapters:
1) Practical considerations when operationalizing ML (supervised learning) 
2) Automated Machine Learning (with examples drawn from AutoGluon)

Link to repo where edits will be made:  https://github.com/jwmueller/d2l-en/tree/practice-auto

**Comment by astonzhang** [comment]
Thanks. Let's sync offline on the detailed plan and workflow.

**Comment by astonzhang** [comment]
Closing after sync.
