### ISSUE TITLE
two tabs' chaos

### ISSUE THREAD

**Issue by StevenJokess** [d2l-ai/d2l-en#1479]
![image](https://user-images.githubusercontent.com/71307974/95062948-41481600-0730-11eb-99cf-197d21ad6d3c.png)
http://preview.d2l.ai/d2l-en/master/chapter_deep-learning-computation/model-construction.html

**Comment by astonzhang** [comment]
There is indeed no compilation content for Pytorch.

**Comment by StevenJokess** [comment]
But, when you click tensorflow, the compilation don't show.
![image](https://user-images.githubusercontent.com/71307974/95156973-64270880-07ca-11eb-869e-e6b1f2731ce3.png)
@astonzhang
