### ISSUE TITLE
[MXNet] Bug in 13.13 Image Classification CIFAR-10 Kaggle

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#1531]
https://d2l.ai/chapter_computer-vision/kaggle-cifar10.html

Probably needs hyperparam tuning since the training is not stable.
![image](https://user-images.githubusercontent.com/23621655/99875527-7cd26d00-2c16-11eb-9362-9f27d9269fdf.png)
![image](https://user-images.githubusercontent.com/23621655/99875547-9ffd1c80-2c16-11eb-8a10-1c9337c90caa.png)

**Comment by astonzhang** [comment]
This is ok because we do expect to just show a working example. We expect readers to practice the exercises to make the results better.
