### ISSUE TITLE
can not open the jupyter notebook from d2l

### ISSUE THREAD

**Issue by Hannibal046** [d2l-ai/d2l-en#1537]
Dear all:

I just downloaded the all jupyter notebooks from the web. And when I open it with my jupyter lab. It give me the 'NotJsonError'. Can anyone help me ?

I am using Macbook pro ,the os is Big Sur.

<img width="1894" alt="image" src="https://user-images.githubusercontent.com/38466901/100064113-0ed3b300-2e6d-11eb-964c-5736de1b0359.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/38466901/100064310-50645e00-2e6d-11eb-8988-a451ad654f85.png">

**Comment by astonzhang** [comment]
Can you try to follow the installation guide https://d2l.ai/chapter_installation/index.html to open those jupyter notebooks?

**Comment by AnirudhDagar** [comment]
@Hannibal046  there are notebooks/sections in the book which are currently under dev for PyTorch and are not ported to PyTorch (Only available in MXNet as of today). Those notebooks (including the one in the screenshot) are actually empty files and you can't open those up. For now you can work with all notebooks till chapter 12 which are available in PyTorch. Please stay tuned and we'll soon release a newer version with all the sections available in PyTorch.
Thanks!

**Comment by Hannibal046** [comment]
> Can you try to follow the installation guide https://d2l.ai/chapter_installation/index.html to open those jupyter notebooks?



> @Hannibal046 there are notebooks/sections in the book which are currently under dev for PyTorch and are not ported to PyTorch (Only available in MXNet as of today). Those notebooks (including the one in the screenshot) are actually empty files and you can't open those up. For now you can work with all notebooks till chapter 12 which are available in PyTorch. Please stay tuned and we'll soon release a newer version with all the sections available in PyTorch.
> Thanks!

ok, thanks! Looking forward to the newer version!

**Comment by AnirudhDagar** [comment]
Closing this for now!
