### ISSUE TITLE
Use native torchvision.io instead of PIL Image

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#1567]
### Issue with PIL
Semantic Segmentation Dataset uses VOC Dataset. When opening and reading multiple images in the function `read_voc_images` with PIL, if repeated multiple times the following IO Error is thrown `IOError: [Errno 24] Too many open files`. This issue is mentioned [here](https://github.com/pytorch/vision/issues/539) as well and seems to be some sort of internal issue with `PIL.Image` module.

### Pitch
We can switch to `torchvision.io.read_images` as soon as the next version of torchvision is released. Currently, this function [supports grayscale images and different image modes](https://github.com/pytorch/vision/pull/3024) in the nightly or source builds only, so we should wait for the next stable release and utilze these.

**Comment by astonzhang** [comment]
That makes sense. Can you send a separate PR to update the build.yml and open & track a separate issue to update the next stable release that includes this feature?
