### ISSUE TITLE
[PyTorch] Add split_f argument to train_batch_ch13

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#1585]
Current pytorch implementation ignores the argument `split_f` in the function `train_batch_ch13` as shown below.

```python
def train_batch_ch13(net, X, y, loss, trainer, devices):
    if isinstance(X, list):
        # Required for BERT Fine-tuning (to be covered later)
        X = [x.to(devices[0]) for x in X]
    else:
        X = X.to(devices[0])
...
```

Todo: Define the argument `split_f` similar to `mxnet` implementation which can then be used to simplify the `train_batch_ch13` function.

```python
def train_batch_ch13(net, X, y, loss, trainer, devices, split_f=d2l.split_batch):
...
```

In this case, we can avoid the conditional `if isinstance` and instead pass `split_f` method which can then handle both:
* single inputs with `split_batch` method to be defined in `chapter_computational-performance/multiple-gpus.md`.
* multi inputs with `split_batch_multi_inputs` method to be defined in `chapter_natural-language-processing-applications/natural-language-inference-attention.md` (as used in BERT Fine-tuning).

**Comment by astonzhang** [comment]
@AnirudhDagar perhaps you may wish to wrap it up when you have time? Later it's hard to recall what we were thinking two months ago :)

**Comment by AnirudhDagar** [comment]
Actually, if I can recall correctly, I later realized that the `split_f` arg in PyTorch won't be possible since we now manually split using `d2l.split_batch` in `chapter_computational-performance/multiple-gpus.md`. But in other PyTorch sections where the concise implementation is used, we don't want to repeat the splitting as `nn.DataParallel` internally does the same. The only thing that we wanted to achieve through the `split_f` arg in pytorch was the `.to(device)` functionality which would let us remove the complexity of `if instance`. 

It is probably better this way, I'm closing this for now. If I find a simpler workaround to avoid the `if instance` conditionals then I'll send a PR. Sorry for raising this and the confusion caused.
