### ISSUE TITLE
[TF ] Update required in Section 8.5.6 Training 

### ISSUE THREAD

**Issue by PHOENIXFURY007** [d2l-ai/d2l-en#1615]
1. please update the images for both the graphs under Tensorflow in training
2. the perplexity value is coming to be near 1 for both while in the given output it is around 17
3. prediction results are not present for the outputs 
``

**Comment by AnirudhDagar** [comment]
@PHOENIXFURY007 these are generated through CI. I think the perplexity is around 1 for `tf` in the latest release as seen [here](http://d2l.ai/chapter_recurrent-neural-networks/rnn-scratch.html). Feel free to re-open this issue if you have any other doubts.
