### ISSUE TITLE
pip install only finds 0.16.0, not 0.16.1

### ISSUE THREAD

**Issue by floriandonhauser** [d2l-ai/d2l-en#1639]
In the Google Colab notebooks, d2l is installed with version 0.16.1
`!pip install d2l==0.16.1`

However, the newest pip version right now seems to be 0.16.0 ([see here](https://pypi.org/project/d2l/#history)).
Therefore, this line will always fail with:
`ERROR: Could not find a version that satisfies the requirement d2l==0.16.1 (from versions: 0.8.2, 0.8.5, 0.8.6, 0.8.7, 0.9.1, 0.9.2, 0.10, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.16.0)
ERROR: No matching distribution found for d2l==0.16.1`

Either, the wrong version number is used in pip or the wrong version is referenced in Google Colab.

**Comment by astonzhang** [comment]
Thanks. We just released the 0.16.1. Can you try again in one or two hours?

**Comment by floriandonhauser** [comment]
Now it works, thank you :)
