### ISSUE TITLE
Fomula 2.4.11 does not make sense

### ISSUE THREAD

**Issue by Banyc** [d2l-ai/d2l-en#1676]
![image](https://user-images.githubusercontent.com/36535895/111339410-b3932e00-86b2-11eb-90be-673ea5a50cc0.png)

This formula is in the ["calculus" section](https://github.com/d2l-ai/d2l-en/blob/83ecc03a240f1e30dc36dd53083b1d5914391bcc/chapter_preliminaries/calculus.md) -> "Chain Rule". If we remove those $du_i$, it becomes

<img src="https://render.githubusercontent.com/render/math?math=\displaystyle \frac{dy}{dx_i} = m \frac{dy}{dx_i}">

**Comment by astonzhang** [comment]
Thanks. You may refer to total derivatives: https://en.wikipedia.org/wiki/Total_derivative

For instance:

![Screen Shot 2021-03-19 at 12 22 40 PM](https://user-images.githubusercontent.com/22279212/111832295-d63d6680-88ad-11eb-9e32-0da8525c7f12.png)

Just reopen this issue if it still doesn't make sense

**Comment by Banyc** [comment]
@astonzhang I hope the additional info about total derivatives can be considered adding to the book as there might be many like me who do not have that knowledge.

Thanks!
