### ISSUE TITLE
Request for Pytorch or Tensorflow version of PDF

### ISSUE THREAD

**Issue by AliAkbarBadri** [d2l-ai/d2l-en#1700]
Hi
Is there any chance to release the PDF of the book in Tensorflow or Pytorch, please?
Thanks.

**Comment by nikisix** [comment]
`jupyter nbconvert mynotebook.ipynb --to pdf`

**Comment by ToddMorrill** [comment]
`jupyter nbconvert geometry-linear-algebraic-ops.ipynb --to pdf` is throwing errors related to svg files. Is there any chance you can compile the PDF version of the textbook using PyTorch?

I'm happy to share more information about the error messages if you think it's an easy fix.

**Comment by VikramKharvi** [comment]
PDF of the book in Tensorflow or Pytorch would be very help full for the community

**Comment by nikisix** [comment]
Few workarounds mentioned here: https://github.com/jupyter/nbconvert/issues/552
godspeed

**Comment by ingambe** [comment]
From the recent commits, the PDF version of Pytorch's notebooks should soon be available officially.
However, for the most impatient one, I put a link to the pdf generation of the Pytorch PDF pull request: http://preview.d2l.ai/d2l-en/PR-1770/d2l-en-pytorch.pdf

**Comment by VikramKharvi** [comment]
Finally!!, Thanks a lot.

**Comment by AnirudhDagar** [comment]
Once #1771 is merged, it should be available in the release `v0.16.5`.

**Comment by astonzhang** [comment]
#1771 is merged. It may take 1 or 2 hours to access the PyTorch pdf on the D2L homepage.
