### ISSUE TITLE
suggestion: rename train_ch3 to something more generic

### ISSUE THREAD

**Issue by murphyk** [d2l-ai/d2l-en#1701]
The [train_ch3](https://github.com/d2l-ai/d2l-en/blob/master/d2l/torch.py#L326) function could be renamed to 'train_loop_v1' or something like that, since it is quite generic, and is used in several chapters (eg sec 4.6 on dropout).

I would also suggest removing the hard-coded assertions about train/test accuracy from this function, since they may fail if different arguments are passed.

Similarly I would rename [predict_ch3](https://github.com/d2l-ai/d2l-en/blob/master/d2l/torch.py#L341) to something like 'predict_fashion_mnist', since you hard-code the assumption about the dataset inside the function.

**Comment by astonzhang** [comment]
Thanks Kevin for the great suggestions!

For assertions, we noticed that our TF implementations often produce random results that have larger variance. Thus we put assertion statements to help our CI server catch those undesirable results that don't match our text descriptions.
