### ISSUE TITLE
suggestion: move sec 4.9 (Environment and Distribution Shift) out of ch 4 (MLPs)

### ISSUE THREAD

**Issue by murphyk** [d2l-ai/d2l-en#1702]
Sec 4.9 (presumably written by Zachary :) does not logically belong in sec 4, since it has nothing to do with MLPs.
(Indeed most of the examples concern image classification.) You might want to move it to a later part of the book. (Adding practical examples with code would also be nice, and would be more in the spirit of the rest of the book :)

**Comment by astonzhang** [comment]
Thanks! We put it right before a full Kaggle example to emphasize how ML in practice may look different than we thought. Besides authors, many other open-source community members also contribute to this section :) Hopefully there'll be contributions of code illustrations soon.
