### ISSUE TITLE
typo in eqn 10.2.7

### ISSUE THREAD

**Issue by murphyk** [d2l-ai/d2l-en#1707]
In the denominator of 10.2.7 in the [kernel regression section](http://d2l.ai/chapter_attention-mechanisms/nadaraya-waston.html), second line, it should be x_j not x_i.

**Comment by astonzhang** [comment]
Thanks Kevin! Fixed at https://github.com/d2l-ai/d2l-en/commit/26a8902723b2c9e33ef3a648f25d892c41a1fb80
