### ISSUE TITLE
caption in fig 12.5.3 is incorrect

### ISSUE THREAD

**Issue by murphyk** [d2l-ai/d2l-en#1717]
Fig 12.5.3 in http://d2l.ai/chapter_computational-performance/multiple-gpus.html has the order of the labels in caption b-c mixed up.

**Comment by astonzhang** [comment]
Thanks Kevin. Are you referring to Fig 12.5.2? This section was recently revised. Does it look good to you now?

**Comment by murphyk** [comment]
yes I meant 12.5.2. The middle two captions should be swapped (layerwise,
then network partitioning)

**Comment by astonzhang** [comment]
Thanks. It was revised.
