### ISSUE TITLE
Add "Open with Google Colab" feature in every notebook

### ISSUE THREAD

**Issue by Rukmini-Meda** [d2l-ai/d2l-en#1736]
The notebooks in this book do not have the feature to run on Google Colab. This feature will be very helpful for those who are just beginning with deep learning and will help us familiarize ourselves with the code in a better way.

**Comment by astonzhang** [comment]
Have you checked out https://d2l.ai/chapter_appendix-tools-for-deep-learning/colab.html

**Comment by smolix** [comment]
Hi @Rukmini-Meda - I'm confused. Every notebook on the site can be launched in Colab. What else would you need? I'm going to close the issue since it seems that what you're asking for has already been implemented for a while.
