### ISSUE TITLE
Search doesn't appear to work

### ISSUE THREAD

**Issue by indigoviolet** [d2l-ai/d2l-en#1737]
Currently, the search page shows no results and just "Preparing search"...

http://d2l.ai/search.html?q=transformer

![image](https://user-images.githubusercontent.com/114010/116157746-5cfe1400-a6a2-11eb-8185-902defd38792.png)

Possibly related to this error in the console:

![image](https://user-images.githubusercontent.com/114010/116157842-8454e100-a6a2-11eb-8c29-07553906d950.png)

**Comment by yoderj** [comment]
It has actually been broken for a few weeks.  Thanks for putting in the issue, @indigoviolet!

**Comment by mli** [comment]
that's due to the api change of sphinx. fixed by https://github.com/mli/mx-theme/commit/8e6d3ceed3f207956c6a3f6239c4b9800f9cd959 it may take a few days to take effect (need to wait a release to update the html). 

@astonzhang  please have a check if the search issue is fixed for next release.

**Comment by astonzhang** [comment]
> that's due to the api change of sphinx. fixed by [mli/mx-theme@8e6d3ce](https://github.com/mli/mx-theme/commit/8e6d3ceed3f207956c6a3f6239c4b9800f9cd959) it may take a few days to take effect (need to wait a release to update the html).
> 
> @astonzhang please have a check if the search issue is fixed for next release.

Thanks. Will do.
