### ISSUE TITLE
Potentially confusing statement in "4.1.1.2. Incorporating Hidden Layers"

### ISSUE THREAD

**Issue by adyomin** [d2l-ai/d2l-en#1764]
> We can overcome these limitations of linear models and handle a more general class of functions by incorporating one or more hidden layers.

Does this statement assume non-linear activations in the hidden layer(s) introduced in 4.1.1.3.? If it does not, could authers please explain why and how adding more layers adds expressive power? And if non-linear activations are assumed, could you please make it explicit?

**Comment by astonzhang** [comment]
Yes, we assume non-linear activations (omitted here before the "activation function" has been undefined yet) as explained in 4.1.1.3.

**Comment by adyomin** [comment]
Thank you for the clarification, this solves the issue for me personally. I'll leave it up to you to close or leave the issue open.
