### ISSUE TITLE
d2l.bleu(fra, translation) -> d2l.bleu(translation, fra)?

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-en#1780]
https://github.com/d2l-ai/d2l-en/blob/master/chapter_attention-mechanisms/bahdanau-attention.md
https://github.com/d2l-ai/d2l-en/blob/master/chapter_attention-mechanisms/transformer.md

@biswajitsahoo1111 , @terrytangyuan , are there any specific reasons why we switch `translation` and `fra` when invoking `d2l.bleu` in the TF implementation? If not, I'd suggest to stay consistent/correct. Thanks!

**Comment by terrytangyuan** [comment]
Fixing in https://github.com/d2l-ai/d2l-en/pull/1782
