### ISSUE TITLE
Inconsistent use of np.dot and torch.mv in Section 2.3.8

### ISSUE THREAD

**Issue by dowobeha** [d2l-ai/d2l-en#1792]
The final paragraph of Section 2.3.8 *Matrix-Vector Products* mentions the use of `np.dot` but not `torch.mv`. The subsequent code examples uses `torch.mv` but not `np.dot`.

Either the text should describe `torch.mv` or the code should use `np.dot`

**Comment by AnirudhDagar** [comment]
Thanks @dowobeha for raising this issue and pointing it out! :)
