### ISSUE TITLE
Minor typo in Figure 9.1.1: `function` misspelled as `fuction`

### ISSUE THREAD

**Issue by GuDzpoz** [d2l-ai/d2l-en#1837]
In [Fig. 9.1.1](https://github.com/d2l-ai/d2l-en/blob/master/img/gru-1.svg) as well as some other diagrams in [9.1. GRU](https://d2l.ai/chapter_recurrent-modern/gru.html), `activation function` is misspelled as `activation fuction`.

![The image](https://github.com/d2l-ai/d2l-en/raw/07c2c8ac4903bb1973deea5870815f0cad426f86/img/gru-1.svg)

**Comment by astonzhang** [comment]
Thanks very much for pointing this out!
It's fixed: https://github.com/d2l-ai/d2l-en/commit/31053e469974410fbd3ffa90cdf23e917f3d84c1
