### ISSUE TITLE
module 'd2l.torch' has no attribute 'load_data_time_machine

### ISSUE THREAD

**Issue by myrainbowandsky** [d2l-ai/d2l-en#1910]
Just checked torch.py. There is no such function. (http://d2l.ai/chapter_recurrent-neural-networks/rnn-concise.html)

**Comment by astonzhang** [comment]
cc @mli 
We have been working on a major API revision that is still ongoing on the master branch.
Please refer to the release branch for the stable 0.17.0 release: https://github.com/d2l-ai/d2l-en/blob/release/d2l/torch.py

**Comment by ant-trullo** [comment]
Hi all,
I have the same problem 
from d2l import torch as d2l
AttributeError: module 'd2l.torch' has no attribute 'HyperParameters'
and
import d2l
AttributeError: module 'd2l.torch' has no attribute 'HyperParameters'

Python 3.8.10 on ubuntu 20.04 and d2l.__version__ 0.17.0
thanks for the help
Ant

**Comment by AnirudhDagar** [comment]
Hi @ant-trullo,

Can you please update your d2l version to the latest alpha release and try again? Thanks!

`pip install --upgrade d2l==1.0.0a0`

**Comment by ant-trullo** [comment]
Hi AnirudhDagar,
now it works. Thanks a lot for your answer.

**Comment by AnirudhDagar** [comment]
Great! I'll close this issue now :))

**Comment by DearDreamer** [comment]
It is so good deal,thanks!

**Comment by NathanZorndorf** [comment]
Same issue - `pip install --upgrade d2l==1.0.0a0` worked for me. Thanks.

**Comment by Bisalia** [comment]
I use pip install --upgrade d2l==1.0.0a0 on google colab  but it not work

AttributeError                            Traceback (most recent call last)
[<ipython-input-223-9ba22995f719>](https://localhost:8080/#) in <cell line: 3>()
      1 # Call the fully implemented HyperParameters class saved in d2l
      2 # Call the fully implemented HyperParameters class saved in d2l
----> 3 class B(d2l.HyperParameters):
      4     def __init__(self, a, b, c):
      5         self.save_hyperparameters(ignore=['c'])

AttributeError: module 'd2l.torch' has no attribute 'HyperParameters'

**Comment by SkyArroww** [comment]
In the latest version of d2l, the load_data_time_machine() seems to be changed into load_data_nmt()
![企业微信截图_20240719165744](https://github.com/user-attachments/assets/20c4fd3a-4aae-4117-8ed9-283277d908d6)

**Comment by sourceheart** [comment]
I use pip install --upgrade d2l on vscode but it not work

still have problem

**Comment by fang19911030** [comment]
> I use pip install --upgrade d2l==1.0.0a0 on google colab but it not work
> 
> AttributeError Traceback (most recent call last) in <cell line: 3>() 1 # Call the fully implemented HyperParameters class saved in d2l 2 # Call the fully implemented HyperParameters class saved in d2l ----> 3 class B(d2l.HyperParameters): 4 def **init**(self, a, b, c): 5 self.save_hyperparameters(ignore=['c'])
> 
> AttributeError: module 'd2l.torch' has no attribute 'HyperParameters'

I have the same issue on google collab

**Comment by jameszhan02** [comment]
> > I use pip install --upgrade d2l==1.0.0a0 on google colab but it not work
> > AttributeError Traceback (most recent call last) in <cell line: 3>() 1 # Call the fully implemented HyperParameters class saved in d2l 2 # Call the fully implemented HyperParameters class saved in d2l ----> 3 class B(d2l.HyperParameters): 4 def **init**(self, a, b, c): 5 self.save_hyperparameters(ignore=['c'])
> > AttributeError: module 'd2l.torch' has no attribute 'HyperParameters'
> 
> I have the same issue on google collab

I guess you need to restart kernel
