### ISSUE TITLE
Hope to implement the code of d2l  based on  paddlepaddle framework

### ISSUE THREAD

**Issue by tngt** [d2l-ai/d2l-en#1914]
Hello, I am the staff of paddlepaddle. We want to implement the code of this book based on paddlepaddle, like pytorch and tensorflow. Currently, chapters 1-7 are being implemented. I hope someone can guide us on the specific process of contributing content to d2l. Looking forward to your reply.

**Comment by astonzhang** [comment]
Thanks! Is it this repo: https://github.com/tngt/Dive-into-DL-paddlepaddle/tree/master/docs

Currently we've been revising the API for the entire book: http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_linear-networks/api.html  Could you see if could adapt using the new API? Besides, we have been revising the chapters quite heavily recently (see the diff between the master branch and the release branch). If you wish to reduce duplicate efforts, you may start adapting after our next release that uses the new API.

**Comment by tngt** [comment]
Thank you very much for your reply. We are currently developing based on the Chinese version of d2l, here: [https://github.com/PaddlePaddle/awesome-DeepLearning/tree/master/Dive-into-DL-paddlepaddle](https://github.com/PaddlePaddle/awesome-DeepLearning/tree/master/Dive-into-DL-paddlepaddle)

Could you tell me when will the Chinese version of the d2l API be updated?

**Comment by tngt** [comment]
Thank you  for your reply and prompt. We are currently developing based on the Chinese version of d2l, here: [https://github.com/PaddlePaddle/awesome-DeepLearning/tree/master/Dive-into-DL-paddlepaddle](https://github.com/PaddlePaddle/awesome-DeepLearning/tree/master/Dive-into-DL-paddlepaddle)

Could you tell me when will the Chinese version of the d2l API be updated?

**Comment by AnirudhDagar** [comment]
Thanks for your work! paddlepaddle is now available in d2l-zh. 🥳
Closing this now.
