### ISSUE TITLE
Animator class can't show images in pycharm project

### ISSUE THREAD

**Issue by duncanlou** [d2l-ai/d2l-en#1961]
I pasted the pytorch.py file to my pycharm projects, and I used the train_ch6 function in my code, but the console window in pycharm could't show any images. The console showed this: "<Figure size 350x250 with 1 Axes>" .    How should I edit the code so that figures will be shown on pycharm?

**Comment by AnirudhDagar** [comment]
@duncanlou, we explicitly set the matplotlib backend to svg format to display plots in jupyter notebooks. You can try changing that or I'd simply suggest using colab/sagemaker/local notebooks for running the code, without worrying about these utility changes.

I don't have pycharm and we don't test our code against a particular editor, so i can't say for sure. But see https://github.com/d2l-ai/d2l-en/blob/eecbef4848647f2cf0d0edd6d8b41dee03f0d95f/d2l/torch.py#L55 maybe changing this works for your specific case.

I'm closing this, for now; feel free to re-open it if the above problem persists.
