### ISSUE TITLE
Update main?

### ISSUE THREAD

**Issue by Melanol** [d2l-ai/d2l-en#1997]
Excuse me, how often do you update the main version of d2l.ai that people see? There are a lot of updates on Github, but I don't see them on d2l.ai English main, only in "http://preview.d2l.ai/d2l-en/PR-{some_number}/", where some some_number is a number I get when I receive conformation of my pull requests.

**Comment by astonzhang** [comment]
The main version of d2l.ai currently hosts stable releases on the https://github.com/d2l-ai/d2l-en/tree/r0.17 branch.
We have been refactoring the master branch like crazy - once it's in a good shape we'll release them on the main website.

**Comment by AnirudhDagar** [comment]
Closing this since we recently added ability to view the live preview version based on the master branch if users want to see the most recent changes.

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/23621655/189449874-bbbcd8cf-5302-417b-9d28-62e72825b097.png">
