### ISSUE TITLE
can't load d2l using colab

### ISSUE THREAD

**Issue by wudiweishao** [d2l-ai/d2l-en#2067]
![1647350617(1)](https://user-images.githubusercontent.com/22288341/158387423-5dd42f34-a9ef-40d0-840a-5a24aa4c6096.png)

**Comment by AnirudhDagar** [comment]
Hi @wudiweishao, thanks for raising the issue. We are aware of the problem. It is due to the lack of python 3.8 support in colab and the latest version of `numpy>=1.22` has dropped python3.7 support. We're working on the issue in #2066. Should be fixed soon.

**Comment by AnirudhDagar** [comment]
Fixed in #2066
