### ISSUE TITLE
[Enhancement] Add related papers to the Universal Approximator section?

### ISSUE THREAD

**Issue by minhlong94** [d2l-ai/d2l-en#2083]
When reading [Section 4.1.1.4](https://d2l.ai/chapter_multilayer-perceptrons/mlp.html#universal-approximators), I am quite interesting that the Neural network can approximate any continuous function, however, it does not provide additional reading materials for this one, which is a bit sad. May I propose adding some related papers in this section, such as [Wang 2017](https://arxiv.org/abs/1702.07800), [Cybenko 1989](https://web.njit.edu/~usman/courses/cs675_fall18/10.1.1.441.7873.pdf), [Hornik 1989](https://www.sciencedirect.com/science/article/abs/pii/0893608089900208) and [Hornik 1991](https://www.sciencedirect.com/science/article/abs/pii/089360809190009T)?

**Comment by astonzhang** [comment]
Thanks. A more updated preview version is at http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_multilayer-perceptrons/mlp.html#universal-approximators

If you think this can be improved, feel free to submit a PR :)

**Comment by minhlong94** [comment]
Hi, the updated preview looks awesome to me. It includes direct citations in the content, which is very helpful. I'll close this issue and be looking forward to its release :)
