### ISSUE TITLE
d2l makes os.environ["CUDA_VISIBLE_DEVICES"] = "1" invalid

### ISSUE THREAD

**Issue by FelliYang** [d2l-ai/d2l-en#2097]
when i try to import d2l into my project, I found if os.environ["CUDA_VISIBLE_DEVICES"] is set after the d2l, then it will be valid.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/38461329/162663129-7294395b-f58a-4de4-8eed-4dde85bd2229.png">
before run this program
![image](https://user-images.githubusercontent.com/38461329/162663286-ca3c50af-e539-4979-9021-38e063509255.png)
when i run this program
![image](https://user-images.githubusercontent.com/38461329/162663342-3598ec8b-5fcf-4417-9f68-933116d92eab.png)
Even though set before the d2l have been imported will work, I still hope this bug can be solved, since it will be more eleglent and convinent.

**Comment by AnirudhDagar** [comment]
Hi @FelliYang,
`CUDA_VISIBLE_DEVICES` is an environment variable which has nothing to do with a python package like `d2l`. We do not set it or unset it anywhere within d2l package. I suggest you to reproduce this issue on a different machine. You can then try to limit the number of GPUs with `CUDA_VISIBLE_DEVICES` env variable.

I'll close this issue for now, let me know in case you need some help with this. Thanks!
