### ISSUE TITLE
A mistake in seq2seq prediction implementation?

### ISSUE THREAD

**Issue by zhmou** [d2l-ai/d2l-en#2134]
https://github.com/d2l-ai/d2l-en/blob/9e4fbb1e97f4e0b3919563073344368755fe205b/d2l/torch.py#L2996-L3030
**Bugs here:**
``` Python
    for _ in range(num_steps):
        Y, dec_state = net.decoder(dec_X, dec_state)
```
As you can see here, dec_state will update in every loop. But it not only affects the hidden state for rnn, but also the context vector for each step. (I don't know why Seq2SeqDecoder seems not implemented in [d2l/torch.py](https://github.com/d2l-ai/d2l-en/blob/9e4fbb1e97f4e0b3919563073344368755fe205b/d2l/torch.py)), In chapter 9.7.2, here wrote:
https://github.com/d2l-ai/d2l-en/blob/9e4fbb1e97f4e0b3919563073344368755fe205b/chapter_recurrent-modern/seq2seq.md?plain=1#L383-L411

![](https://raw.githubusercontent.com/d2l-ai/d2l-en/9e4fbb1e97f4e0b3919563073344368755fe205b/img/seq2seq-predict.svg)

And according to this graph, the correct approach should be to keep the context vector always constant at each time step.
(there is no problem with this method when training, because the target sentence is complete and context vector is already broadcast in every time step)

**My Solution(Not tested):**
Modify  Seq2SeqDecoder:
``` Python
class Seq2SeqDecoder(d2l.Decoder): 
     """The RNN decoder for sequence to sequence learning.""" 
     def __init__(self, vocab_size, embed_size, num_hiddens, num_layers, 
                  dropout=0): 
         super().__init__() 
         self.embedding = nn.Embedding(vocab_size, embed_size) 
         self.rnn = d2l.GRU(embed_size+num_hiddens, num_hiddens, 
                            num_layers, dropout) 
         self.dense = nn.LazyLinear(vocab_size) 
         self.apply(init_seq2seq) 
              
     def init_state(self, enc_outputs, *args): 
         return enc_outputs[1]  
     
     # Add a parameter here:
     def forward(self, X, enc_state, enc_final_layer_output_at_last_step): 
         # X shape: (batch_size, num_steps) 
         # embs shape: (num_steps, batch_size, embed_size) 
         embs = self.embedding(d2l.astype(d2l.transpose(X), d2l.int32)) 
         # context shape: (batch_size, num_hiddens)            
         # Broadcast context to (num_steps, batch_size, num_hiddens) 
         context = enc_final_layer_output_at_last_step.repeat(embs.shape[0], 1, 1)             
         # Concat at the feature dimension 
         embs_and_context = d2l.concat((embs, context), -1) 
         outputs, state = self.rnn(embs_and_context, enc_state) 
         outputs = d2l.swapaxes(self.dense(outputs), 0, 1) 
         # outputs shape: (batch_size, num_steps, vocab_size) 
         # state shape: (num_layers, batch_size, num_hiddens) 
         return outputs, state 
```
Modify [EncoderDecoder](https://github.com/d2l-ai/d2l-en/blob/9e4fbb1e97f4e0b3919563073344368755fe205b/d2l/torch.py#L864-L868):
``` Python
    def forward(self, enc_X, dec_X, *args):
        enc_outputs = self.encoder(enc_X, *args)
        dec_state = self.decoder.init_state(enc_outputs, *args)
        # Return decoder output only
        return self.decoder(dec_X, dec_state, enc_outputs[1][-1])[0]
```

Modify predict_seq2seq():
``` Python
    for _ in range(num_steps):
        Y, dec_state = net.decoder(dec_X, dec_state, enc_outputs[1][-1])
```

**Comment by cheungdaven** [comment]
I am wondering if this is related to the tf issue in transformer? @AnirudhDagar

**Comment by astonzhang** [comment]
Thanks! Please see fix in https://github.com/d2l-ai/d2l-en/pull/2408
