### ISSUE TITLE
[Question] How to determine train, test iteration and vocab?

### ISSUE THREAD

**Issue by teohsinyee** [d2l-ai/d2l-en#2141]
Greetings.

I want to fit this code with my personal dataset. Not the IMDB ones. The `load_data_imdb()` returns 3 parameters. 
To fit my dataset in, I've to set the 3 parameters right? But what value should I put?

Reference: https://classic.d2l.ai/chapter_natural-language-processing/sentiment-analysis.html#put-all-things-together
```import torch
from torch import nn
from d2l import torch as d2l

batch_size = 64

train_iter, test_iter, vocab = d2l.load_data_imdb(batch_size) 
```

**Comment by AnirudhDagar** [comment]
To use your own dataset, you will need to change the `read_imdb` function to `read_your_custom_data` function and then call it from `load_data_custom`.

**Comment by teohsinyee** [comment]
> load_data_custom

Hi @AnirudhDagar, do you mind providing the URLs to the documentation for both methods `read_your_custom_data` and `load_data_custom`? I tried to search but can't find it.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/56106630/170942162-bf509eb2-e646-479c-8481-fa3325f1dbd2.png">

**Comment by AnirudhDagar** [comment]
@teohsinyee there is no `load_data_custom`, I just meant that you may want to refactor `load_data_imdb` method to the new dataset name. Logic inside the function will remain the same.
