### ISSUE TITLE
[PyTorch] AttributeError: module 'd2l.torch' has no attribute 'trim_pad'

### ISSUE THREAD

**Issue by teohsinyee** [d2l-ai/d2l-en#2142]
I was running https://classic.d2l.ai/chapter_natural-language-processing/sentiment-analysis.html#padding-to-the-same-length
```
num_steps = 15 
train_features = nd.array([d2l.trim_pad(vocab[line], num_steps, vocab.unk) for line in train_tokens])
```

And it gave me this error:

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-cebd7e31a745> in <module>
      1 num_steps = 15  # sequence length
      2 train_features = nd.array([d2l.trim_pad(vocab[line], num_steps, vocab.unk)
----> 3                           for line in train_tokens])
      4 train_features.shape

<ipython-input-42-cebd7e31a745> in <listcomp>(.0)
      1 num_steps = 15  # sequence length
      2 train_features = nd.array([d2l.trim_pad(vocab[line], num_steps, vocab.unk)
----> 3                           for line in train_tokens])
      4 train_features.shape

AttributeError: module 'd2l.torch' has no attribute 'trim_pad'```

**Comment by teohsinyee** [comment]
I resolved this error by writing` trim_pad()` explicitly
![image](https://user-images.githubusercontent.com/56106630/170218775-b0398044-5b48-4584-bf42-ed3d6b2b0e12.png)

The users probably will got same error when following steps mentioned here: https://classic.d2l.ai/chapter_natural-language-processing/sentiment-analysis.html#padding-to-the-same-length

Hope the issue can be fixed.

**Comment by AnirudhDagar** [comment]
Hi @teohsinyee, `trim_pad` is no longer available and has been refactored to `truncate_pad` in the latest d2l package. If you would like to use [classic.d2l.ai](https://classic.d2l.ai) as a reference, please use `pip install d2l==0.10.3` for the corresponding d2l library as mentioned in the [installation section](https://classic.d2l.ai/chapter_install/install.html). I'll close this for now, feel free to reopen it if this doesn't fix your issue.
