### ISSUE TITLE
Bahdanau attention (attention mechanisms) tensorflow notebook build fails in Turkish version.

### ISSUE THREAD

**Issue by semercim** [d2l-ai/d2l-en#2218]
Currently, PR-63 (Fixing more typos) builds fail only for tensorflow notebook. I could not figure out the reason. @AnirudhDagar , I would be glad if you could take a look.

**Comment by AnirudhDagar** [comment]
I'm closing this issue as I mentioned on the PR about this not being a specific issue. The problem with [CI timeouts](http://ci.d2l.ai/blue/organizations/jenkins/d2l-tr/detail/PR-63/23/pipeline) on multiple builds recently could have happened for various flaky reasons. Atm the d2l-ai/d2l-tr#63 is green, and I'll merge that.
