### ISSUE TITLE
issue with module show_list_len_pair_hist from d2l.torch

### ISSUE THREAD

**Issue by ulfat191** [d2l-ai/d2l-en#2226]
![image](https://user-images.githubusercontent.com/50806191/181920373-59069fe5-b955-41a8-967a-0ac796053cc8.png)

**Comment by astonzhang** [comment]
It's in our lib: https://github.com/d2l-ai/d2l-en/blob/master/d2l/torch.py#L852

Have you followed the installation guide: https://d2l.ai/chapter_installation/index.html
Specifically, `pip install d2l==1.0.0a0`

**Comment by ulfat191** [comment]
thank you! 
Its working now, i did not update the d2l last time.
