### ISSUE TITLE
Regarding Momentum 

### ISSUE THREAD

**Issue by BalajiAI** [d2l-ai/d2l-en#2232]
Following https://github.com/d2l-ai/d2l-en/pull/2228
@astonzhang The title is also called momentum. It should be originally called velocity. Since momentum is just another hyperparameter and velocity is the one which stores the leaky averages of the past gradients.
I mentioned this because in the book, you spoke about CNN's are performing cross-correlation and not convolution (strictly speaking).

**Comment by astonzhang** [comment]
Although v is velocity, this method is called momentum. See e.g., http://proceedings.mlr.press/v28/sutskever13.pdf

**Comment by BalajiAI** [comment]
Ok. Got it. Thanks @astonzhang

Kind Regards,
Balaji
