### ISSUE TITLE
5x5 convolution padding should be 2 in nin.svg

### ISSUE THREAD

**Issue by zhenjiaguo** [d2l-ai/d2l-en#2311]
According to the code, 5x5 convolution padding should be 2 in nin.svg.

https://github.com/d2l-ai/d2l-en/blob/1dce6bdd62cae2f8fc32815d6a33b7f0412fd68b/chapter_convolutional-modern/nin.md?plain=1#L134-L144

![](https://github.com/d2l-ai/d2l-en/raw/master/img/nin.svg)

**Comment by AnirudhDagar** [comment]
Thanks for raising this @zhenjiaguo, yes we'll update the figure. @astonzhang what is the process to make changes to figures? I don't think I've the software we use to generate these SVGs.

**Comment by astonzhang** [comment]
@zhenjiaguo Thanks! it's fixed
