### ISSUE TITLE
How to load d2l modules on Colab to avoid ModuleNotFoundError?

### ISSUE THREAD

**Issue by coloedrainbow** [d2l-ai/d2l-en#2323]
I’d like to begin reading this book and running its examples. However, for some resoans I am not allowed to install Conda on the machine. So, I have tried to run notebook on colab. However, once running the first cell, it give an Error like this:
```
%matplotlib inline
import math
import time
import numpy as np
import torch
from d2l import torch as d2l

```

```

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7a344dafd5da> in <module>
      4 import numpy as np
      5 import torch
----> 6 from d2l import torch as d2l

ModuleNotFoundError: No module named 'd2l'

```
Any thought on this that might help?

**Comment by AnirudhDagar** [comment]
Hi @coloedrainbow,
Please install latest version of d2l package before using the d2l module: `pip install d2l==1.0.0a1.post0`

**Comment by coloedrainbow** [comment]
Thank @AnirudhDagar it worked. So, do I need to have this line in every notebook that I'm running?

And what is inside d2l that when I wanted to use plt.plt  insteased of d2l.plot it is still not working? (after importing matplotlib, of course)

**Comment by AnirudhDagar** [comment]
You can take a look at the d2l library [here](https://github.com/d2l-ai/d2l-en/tree/master/d2l). It is essentially a set of saved functions and classes, along with some utility methods for plotting etc.

And yes you need to install d2l package wherever it is imported. If you use a local machine, then you can just install it once in your environment. But if you spawn a new colab notebook every time, then you will have to install `d2l` just like any other package.

**Comment by manhcntt21** [comment]
Hi, I use windows os

I run 
```
pip install d2l==1.0.0a1.post0
```
After, this error still appear

![image](https://user-images.githubusercontent.com/27800932/202851863-ba80df89-e65e-4087-abc3-81f8588541b7.png)

lib in conda enviroment


![image](https://user-images.githubusercontent.com/27800932/202851892-872060a5-28ae-4a22-a3cb-306068333862.png)

How to fix this?

**Comment by anonymous-sc** [comment]
> Hi, I use windows os
> 
> I run
> 
> ```
> pip install d2l==1.0.0a1.post0
> ```
> 
> After, this error still appear
> 
> ![image](https://user-images.githubusercontent.com/27800932/202851863-ba80df89-e65e-4087-abc3-81f8588541b7.png)
> 
> lib in conda enviroment
> 
> ![image](https://user-images.githubusercontent.com/27800932/202851892-872060a5-28ae-4a22-a3cb-306068333862.png)
> 
> How to fix this?

Have you activated the conda environment (`conda activate d2l`) when running `jupyter notebook`? See https://d2l.ai/chapter_installation/index.html

**Comment by astonzhang** [comment]
> Hi, I use windows os
> 
> I run
> 
> ```
> pip install d2l==1.0.0a1.post0
> ```
> 
> After, this error still appear
> 
> ![image](https://user-images.githubusercontent.com/27800932/202851863-ba80df89-e65e-4087-abc3-81f8588541b7.png)
> 
> lib in conda enviroment
> 
> ![image](https://user-images.githubusercontent.com/27800932/202851892-872060a5-28ae-4a22-a3cb-306068333862.png)
> 
> How to fix this?

Have you activated the conda environment (conda activate d2l) when running jupyter notebook? See https://d2l.ai/chapter_installation/index.html

**Comment by manhcntt21** [comment]
Hi
Before run jupyter notebook, i activated eviroment conda (conda activate d2l)

**Comment by astonzhang** [comment]
> Hi Before running jupyter notebook, i activated eviroment conda (conda activate d2l)

Here are tips you may try one by one:

1. Did you run `jupyter notebook` in cmd line after `conda activate d2l` on Windows?
2. Can you check if you're using the correct Python kernel (right corner of Jupyter notebook) with d2l in your notebook?
3. Run `!pip install d2l==1.0.0a1.post0` in a code cell of Jupyter notebook

**Comment by manhcntt21** [comment]
I tried all, but not working
