### ISSUE TITLE
FEAT: Add ability to order framework execution in CI

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#2355]
With PRs having a number of changes to a specific framework, it would be useful to tell the CI somehow (maybe through a specific comment in PR description or commit) that the user would like to evaluate for example JAX framework first.

How is this useful?
If I know that I've made changes in JAX tabs only, then maybe I'd like to see if CI is passing or failing for JAX ASAP. Instead of waiting for all other frameworks to finish execution and only at the end JAX is executed. This will make the fail iterate process faster for large PRs.

Not a very urgent, but a nice to have feature in the future.

cc @astonzhang

**Comment by astonzhang** [comment]
Agreed. It's a nice feature to have.

**Comment by AnirudhDagar** [comment]
Closing this as fixed, since Github Actions CI, evaluates all the frameworks parallelly. Hence this feature is not needed anymore.
