### ISSUE TITLE
Issue in 2.4. Calculus

### ISSUE THREAD

**Issue by uhasker** [d2l-ai/d2l-en#2363]
In [2.4. Calculus](https://raw.githubusercontent.com/d2l-ai/d2l-en/master/chapter_preliminaries/calculus.md) the sentence

> Thus, the area of the **triangle** approaches
$n \cdot r \cdot \frac{1}{2} (2 \pi r/n) = \pi r^2$.

should be 

> Thus, the area of the **polygon** approaches
$n \cdot r \cdot \frac{1}{2} (2 \pi r/n) = \pi r^2$.

Alternatively:

> The area of each **triangle** approaches
$\frac{1}{2} \cdot height \cdot base = \frac{1}{2} \cdot r \cdot (2 \pi r/n) =\pi r^2 / n$
and therefore the area of the **polygon** approaches $\pi r^2$.

**Comment by astonzhang** [comment]
@uhasker Thanks! Would you like to become a D2L contributor by sending a PR (see 20.6.1 in https://d2l.ai/chapter_appendix-tools-for-deep-learning/contributing.html#submitting-minor-changes)?

**Comment by uhasker** [comment]
PR is at https://github.com/d2l-ai/d2l-en/pull/2364
