### ISSUE TITLE
Discussion Forum Not Showing up on Classic Branch

### ISSUE THREAD

**Issue by Vortexx2** [d2l-ai/d2l-en#2421]
As the below image shows, none of the lessons on the classic website have functioning discussion forums (eg. http://classic.d2l.ai/chapter_recurrent-modern/beam-search.html). :

![image](https://user-images.githubusercontent.com/68988130/209844458-73b8d19c-ff53-4e83-9977-ea7912787c1c.png)

I've checked it on Firefox and Edge already, I don't think this is browser related.

**Comment by astonzhang** [comment]
https://classic.d2l.ai/chapter_recurrent-modern/beam-search.html

Plz use https

**Comment by Vortexx2** [comment]
Yes, discussions on the https versions work well. My bad!
