### ISSUE TITLE
What is #@save mean and how does it work?

### ISSUE THREAD

**Issue by likefallwind** [d2l-ai/d2l-en#2431]
In the book, teacher says @save is used to save the function we design. I wonder how it work? Is it a character of python？ Or it is designed by d2l？

There is a code here: https://github.com/d2l-ai/d2l-en/blob/master/d2l/torch.py

So the same name function will overwrite function here?

**Comment by AnirudhDagar** [comment]
This is not python functionality. We parse #@save symbol through [d2lbook](https://github.com/d2l-ai/d2l-book) using the `d2lbook build lib` command, which then saves the functions and classes to the respective library file: d2l/framework_name.py

**Comment by likefallwind** [comment]
> This is not python functionality. We parse #@save symbol through [d2lbook](https://github.com/d2l-ai/d2l-book) using the `d2lbook build lib` command, which then saves the functions and classes to the respective library file: d2l/framework_name.py

I see, thanks！
