### ISSUE TITLE
Error when installing gym==0.21.0 from the setup.py

### ISSUE THREAD

**Issue by luisfvc** [d2l-ai/d2l-en#2443]
Hello,
When trying to install the package `d2l==1.0.0b0` I get the following error:

![image](https://user-images.githubusercontent.com/47660358/219097430-f36b8ec7-2dd2-4b3e-b3e6-bc538a2ffb73.png)

This doesn't happen when installing `gym==0.22.0`, for example.
Is it only me? By the way I am really having troubles with the d2l/torch.py module, some classes do not run smoothly.
Regards

**Comment by znacloud** [comment]
Same error occurred to me

**Comment by PicoJr** [comment]
Hello, it seems to relate to this issue: https://github.com/openai/gym/issues/3176

I managed to install `d2l==1.0.0b0` by downgrading my `setuptools` version as described by this comment: https://github.com/openai/gym/issues/3176#issuecomment-1408598628

**Comment by mqy** [comment]
> Hello, it seems to relate to this issue: [openai/gym#3176](https://github.com/openai/gym/issues/3176)
> 
> I managed to install `d2l==1.0.0b0` by downgrading my `setuptools` version as described by this comment: [openai/gym#3176 (comment)](https://github.com/openai/gym/issues/3176#issuecomment-1408598628)

`pip install setuptools==66` works as well.

**Comment by znacloud** [comment]
> > Hello, it seems to relate to this issue: [openai/gym#3176](https://github.com/openai/gym/issues/3176)
> > I managed to install `d2l==1.0.0b0` by downgrading my `setuptools` version as described by this comment: [openai/gym#3176 (comment)](https://github.com/openai/gym/issues/3176#issuecomment-1408598628)
> 
> `pip install setuptools==66` works as well.

Good, it works for me too. Thanks.

**Comment by IfyAnene7** [comment]
> > Hello, it seems to relate to this issue: [openai/gym#3176](https://github.com/openai/gym/issues/3176)
> > I managed to install `d2l==1.0.0b0` by downgrading my `setuptools` version as described by this comment: [openai/gym#3176 (comment)](https://github.com/openai/gym/issues/3176#issuecomment-1408598628)
> 
> `pip install setuptools==66` works as well.

Works for me as well. Thanks!

**Comment by rasoolfa** [comment]
new gym has indeed breaking backward compatibility, I have to double check that too.
yes, will do it by end of the week.

**Comment by AnirudhDagar** [comment]
Hey @rasoolfa, any updates on the use of `gymnasium`? We plan a release soon with the latest versions of all the frameworks/libraries. It would be great if we could also update the two-year-old pinned version of `gym` we are currently using.

**Comment by AnirudhDagar** [comment]
This should be fixed in the master and will reflect in the next release. Closing now!

**Comment by analytics-ceew** [comment]
While trying to pip install d2l

  import pkg_resources
        File "C:\Users\Vaibhav\AppData\Local\Temp\pip-build-env-a7rqgyqr\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
