### ISSUE TITLE
[quick fix included] All colab fail to run due to errors when installing d2l library at start

### ISSUE THREAD

**Issue by gab-chen** [d2l-ai/d2l-en#2474]
A temporary solution is [here](https://github.com/d2l-ai/d2l-en/issues/2443), but it is short-term.

`!pip install d2l==1.0.0-beta0
`is giving an error. 
```python
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from d2l==1.0.0-beta0) (0.1.6)
Collecting gym==0.21.0
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 34.7 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

As a result, none of the Colab notebooks are runnable. 
```python
from d2l import torch as d2l

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-bfd48583f4e9>](https://localhost:8080/#) in <cell line: 5>()
      3 import torch
      4 from torch import nn
----> 5 from d2l import torch as d2l

ModuleNotFoundError: No module named 'd2l'
``` 

You can use this one as an example. 
https://colab.research.google.com/github/d2l-ai/d2l-pytorch-colab/blob/master/chapter_attention-mechanisms-and-transformers/transformer.ipynb#scrollTo=10959c39

**Comment by anonymouslei** [comment]
The same and `pip install setuptools==65.5.0` does not work

**Comment by thelichenhao** [comment]
I tried `!pip install d2l==1.0.0a0` and it works for most chapters.

**Comment by anonymouslei** [comment]
@gab-chen you can try `pip install setuptools==66`. it works for me.
related issue: https://github.com/d2l-ai/d2l-en/issues/2443#issuecomment-1455128143

**Comment by gab-chen** [comment]
> @gab-chen you can try `pip install setuptools==66`. it works for me. related issue: [#2443 (comment)](https://github.com/d2l-ai/d2l-en/issues/2443#issuecomment-1455128143)

Thanks. I have mentioned this temporary solution at the start of the post. Still looking for a long term solution for the benefits of those beginners who are unfamiliar with the dependency system.

**Comment by gab-chen** [comment]
> !pip install d2l==1.0.0a0

Thanks for sharing that. how did you find out the version number that works?

**Comment by thelichenhao** [comment]
@gab-chen You are welcome. I checked the package version history on Pypi and tried some version on Colab.

**Comment by Lazarus657** [comment]
it works,thank you!!!

**Comment by minjae35** [comment]
`pip install d2l==1.0.0a0` works, but when I try to run `d2l.plt.imread()` on google colab, it says directory not found.

**Comment by AnirudhDagar** [comment]
Please follow the quick fix mentioned here: https://github.com/d2l-ai/d2l-en/issues/2489#issuecomment-1547392040

`!pip install git+https://github.com/d2l-ai/d2l-en.git`

**Comment by AnirudhDagar** [comment]
This should be fixed in the master and will reflect in the next release. Closing now!
