### ISSUE TITLE
installing d2l package on google colab

### ISSUE THREAD

**Issue by minjae35** [d2l-ai/d2l-en#2489]
I've tried to run the codes on google colab.
So I tried `pip install d2l==1.0.0-beta0`, but didn't work.
So I used `pip install d2l==1.0.0-alpha0`, and tried to run the following code.
```python
d2l.set_figsize()
img = d2l.plt.imread('../img/catdog.jpg')
d2l.plt.imshow(img);
```
But it says `FileNotFoundError: [Errno 2] No such file or directory: '../img/catdog.jpg'`
How can I run codes in this book on google colab?😭

**Comment by AnirudhDagar** [comment]
We've fixed the issue in the master branch, and it will be released soon. Till then, you can try the following, 
`!pip install git+https://github.com/d2l-ai/d2l-en.git`

For this particular block of code, the image is not copied if you click the link on the website to open the colab notebook.
To fix that, one may do the following:

```python
import PIL
import urllib
img=PIL.Image.open(urllib.request.urlopen('https://github.com/d2l-ai/d2l-pytorch-colab/blob/master/img/catdog.jpg?raw=true'))
d2l.plt.imshow(img);
```

If you don't want to change any code cell, you may open the git repository hosting all the colab notebooks directly in colab
https://github.com/d2l-ai/d2l-pytorch-colab/

This will make sure, the img directory is available locally and then you can simply avoid the URL to open the img.

I hope this solves your issue for now. Let me know in case the problem still persists :)
