### ISSUE TITLE
An Unneeded Semicolon and an Advise in Chapter 3.2.1

### ISSUE THREAD

**Issue by Cwulaek** [d2l-ai/d2l-en#2502]
![image](https://github.com/d2l-ai/d2l-en/assets/30312983/77223fc6-0bb9-4cc8-b5e2-db7070f6c77a)
#### `d2l.plt.show()`

**Comment by AnirudhDagar** [comment]
Hi @Cwulaek, I think you are referring to Section 3.2.1 from zh.d2l.ai.

Anyway, the semicolon is used for displaying the plot only. Otherwise, on running the cell, we'll get unwanted info like `<matplotlib.collections.PathCollection at 0x7f1c4e007040>`.

Closing this now!
