### ISSUE TITLE
Use of deprecated torch.norm

### ISSUE THREAD

**Issue by dhzdhd** [d2l-ai/d2l-en#2528]
The PyTorch examples in the `Norms` section of [Preliminaries - Linear Algebra](http://preview.d2l.ai/d2l-en/master/chapter_preliminaries/linear-algebra.html#dot-products) contain the usage of `torch.norm`.

According to [torch docs](https://pytorch.org/docs/stable/generated/torch.norm.html) `torch.norm` is deprecated and `torch.linalg.vector/matrix_norm` should be used.

I can help in contributing to fixing the issue if this is indeed a problem

**Comment by AnirudhDagar** [comment]
Thanks @dhzdhd for raising the issue. Yeah, we'll welcome a PR with the fix that you already mention.

It would be great to check the usage of torch.norm throughout the book (search entire repo cmd+f) and replace wherever encountered.

**Comment by dhzdhd** [comment]
Alright, i would like to work on this.

**Comment by dhzdhd** [comment]
Unable to proceed due to https://github.com/d2l-ai/d2l-book/issues/75
