### ISSUE TITLE
Up to date ipynb notebooks and pdf versions

### ISSUE THREAD

**Issue by csantosb** [d2l-ai/d2l-en#2539]
Hello, thanks for this great work, this is really amazing and very useful.

I'm wondering if there is  an up to date version of this book in notebook (ipynb) format. Similarly, it would be great to have it in pdf.

Thanks again,

**Comment by AnirudhDagar** [comment]
Hi, yes we have the updated notebooks for all the chapters in https://github.com/d2l-ai/d2l-pytorch-colab
You can also find repos for other frameworks updated notebooks on github with `d2l-ai/d2l-<framework_name>-colab`
