### ISSUE TITLE
PyTorch Colab of Chapter 13.5  is having an IndexError

### ISSUE THREAD

**Issue by gab-chen** [d2l-ai/d2l-en#2562]
Chapter 13.5 Training on Multiple GPUs
13.5.5. Distributing Data
IndexError: list index out of range
![image](https://github.com/d2l-ai/d2l-en/assets/33608782/f3be54a1-b3c1-4aac-a9fc-f08983a8b8fa)

**Comment by gab-chen** [comment]
@AnirudhDagar Can you take a look when available? 
Found that you adapted the code to PyTorch.

**Comment by AnirudhDagar** [comment]
Hi @gab-chen, on google colab, you can only use one GPU, that is the limit from Google. This section of the book will probably fail on colab until they add multi gpu support. You can try to test the code in an environment where you have multiple gpus, and should be just fine.
