### ISSUE TITLE
The discussion link can not be accessed.

### ISSUE THREAD

**Issue by AXYZdong** [d2l-ai/d2l-en#2581]
The discussion link [https://discuss.d2l.ai/](https://discuss.d2l.ai/) can not be accessed.

![image](https://github.com/d2l-ai/d2l-en/assets/45477220/eaef03ab-6c75-4cfa-98b5-3fe220805016)

**Comment by AnirudhDagar** [comment]
Hi @AXYZdong, request your patience, working to resolve the issue. thank you!

**Comment by JH-Lam** [comment]
> Hi @AXYZdong, request your patience, working to resolve the issue. thank you!

hi, how's it going?

**Comment by JH-Lam** [comment]
It seems like this course starts to go into a decline...

**Comment by AnirudhDagar** [comment]
Closing, as fixed now. You can access the discussion link at https://discuss.d2l.ai

**Comment by awayzjj** [comment]
Hi, @AnirudhDagar, the discussion link https://discuss.d2l.ai/ can not be accessed again after your fix.

**Comment by awayzjj** [comment]
@AnirudhDagar I saw “Welcome to NGINX!” before, but it's working fine now.  Thanks！

**Comment by 1195655796** [comment]
> Interesting, it's working just fine for me. Is there any specific error you see? Could you try removing cookies?

the issue happened again！

**Comment by 1195655796** [comment]
@AnirudhDagar could you fix the issue again?thanks!
