### ISSUE TITLE
AutoMl

### ISSUE THREAD

**Issue by hassaanseeker** [d2l-ai/d2l-en#412]
Can a chapter on AutoMl for deep learning on cell and network architecture search included on image segmentation

**Comment by astonzhang** [comment]
AutoML is on my radar, not AutoMI

**Comment by hassaanseeker** [comment]
Sure it has been on my Radar not radar for a long time.

**Comment by smolix** [comment]
@hassaanseeker - stay tuned. We need to get our software support for AutoML taken care of first. There's a lot of ground to cover here, many different algorithms. Once this is done we can teach it, but good code comes first.
