### ISSUE TITLE
Incomplete sentence in section 6.1.2

### ISSUE THREAD

**Issue by hcho3** [d2l-ai/d2l-en#462]
The last sentence in section 6.1.2 ("Constraining the MLP") is currently incomplete.

> This, in a nutshell is the convolutional layer. When the local region (also called a receptive field) is small, the difference as compared to a fully-connected network can be dramatic. While previously, we might have required billions of parameters to represent just a single layer in an image-processing network, we now typically need just a few hundred. The price that we pay for this drastic modification is that our features will be translation invariant and that our layer can only take local information into account. All learning depends on imposing inductive bias. **When that bias agrees with reality, we get sample-efficient models that generalize well to unseen data. But of course, if those biases do not agree with reality, e.g. if images turned out not to be translation invariant,** [the sentence ends here]

I suppose the sentence should say something like "the model will fail to generalize"

**Comment by mli** [comment]
@astonzhang

**Comment by astonzhang** [comment]
Thanks and Fixed.
