### ISSUE TITLE
A glitch in section 2.4.11

### ISSUE THREAD

**Issue by PaulCCCCCCH** [d2l-ai/d2l-en#550]
> You might notice that norms sound a lot like measures of distance. And if you remember Euclidean distances (think Pythagoras’ theorem) from grade school, then the concepts of non-negativity and the triangle inequality might ring a bell. In fact, the Euclidean distance is a norm: specifically it is the  ℓ2  norm. Suppose that the elements in the  𝑛 -dimensional vector  𝐱  are  𝑥1,…,𝑥𝑛 . The **:math:ell_2** norm of  𝐱  is the square root of the sum of the squares of the vector elements:

`ell_2` is not displayed properly here.

**Comment by astonzhang** [comment]
Thanks. 
Fix: https://github.com/d2l-ai/d2l-en/commit/e0a4b36f92416bcc1e2453d48da683a206820c73
