### ISSUE TITLE
Add build instruction

### ISSUE THREAD

**Issue by jjangga0214** [d2l-ai/d2l-en#565]
For contributors, please describe how to build the book (html, pdf, or live server).

**Comment by mli** [comment]
@astonzhang we should have a document for how to build the HTML (without evaluation).

The easiest way is first 

```bash
pip install git+https://github.com/d2l-ai/d2l-book
```

Then change `eval_notebook = True` to `eval_notebook = False` in `config.ini`,

then `d2lbook build html`

Building PDF needs latex and others:

- Latex for PDF sudo apt-get install texlive-full librsvg2-bin
- Fonts for PDF
```
wget https://raw.githubusercontent.com/d2l-ai/utils/master/install_fonts.sh
sudo bash install_fonts.sh
```
- Install pandoc, sudo apt-get install pandoc

**Comment by astonzhang** [comment]
Done: https://github.com/d2l-ai/d2l-en/commit/abf419e8507f34bd058956acfbecd0a2b7546f36

**Comment by jjangga0214** [comment]
@astonzhang 
Which branch is the commit in?

**Comment by jjangga0214** [comment]
@mli @astonzhang Thanks for the response.
I'd like to also modify/contribute to https://github.com/d2l-ai/d2l-ko/. 
It's created in April, so it doesn't have `config.ini`. 

I also just tried 
```bash
pip install git+https://github.com/d2l-ai/d2l-book && d2lbook build html
```
but an error occurred.

The real problem is that the repo(https://github.com/d2l-ai/d2l-ko/) is not active.
I've also made PRs and issues 10 days ago, but no response. Actually they seems not responding to any PRs/issues since July.

Would you let me know how to build it?

**Comment by astonzhang** [comment]
The commands above only apply to d2l-en for now.
For the other repos, just follow
https://github.com/d2l-ai/d2l-zh/blob/master/INFO.md
