### ISSUE TITLE
wrong equations in 10.3. Gradient Descent

### ISSUE THREAD

**Issue by pedro-abundio-wang** [d2l-ai/d2l-en#572]
In 10.3.3.2. Convergence Analysis
equations (10.3.10) is wrong, the denominator in right equations should be second order derivative 

![image](https://user-images.githubusercontent.com/50159788/68563007-1b19e780-0487-11ea-846c-87846411155d.png)

**Comment by mli** [comment]
@astonzhang

**Comment by astonzhang** [comment]
Thanks. We've fixed it earlier.
