### ISSUE TITLE
Question about the table of contents

### ISSUE THREAD

**Issue by HeYDwane3** [d2l-ai/d2l-en#604]
Hi, 

I have a question about how to show the materials as the table of contents of the book in the Jupyter Notebook.

I saw there is an index.ipynb in most folders, I assume this is to show the materials as the order of the table of contents of the book. So I am wondering how can we take advantage of index.ipynb to sort other things? As now all the files can only be sorted by time, name, or size.

Thanks in advance.

**Comment by mli** [comment]
That's a little bit tricky since the TOC format follows sphinx instead of jupyter. We may improve in a future release
