### ISSUE TITLE
How can this be used in AWS SageMaker?

### ISSUE THREAD

**Issue by kornatzky** [d2l-ai/d2l-en#620]
Cannot figure out how to use this code in a AWS SageMaker notebook instance. 
The standard conda_mxnet_p36 kernel does not support, 
```
from mxnet import np, npx
npx.set_np()
```
Get the message cannot import np

**Comment by astonzhang** [comment]
it will be available in 1.6.0 (not released yet)
for now, you can try nightly build, such as
pip install mxnet==1.6.0b20190915
or the cuda version

**Comment by astonzhang** [comment]
Besides, before the MXNet 1.6.0 release, you may try a later nightly build via pypi:

pip install mxnet==1.6.0b20191122
or the cuda version such as
pip install mxnet-cu101==1.6.0b20191122

**Comment by mli** [comment]
@kornatzky  we added a new section to explain how to use sagemaker 
http://d2l.ai/chapter_appendix-tools-for-deep-learning/sagemaker.html
