### ISSUE TITLE
d2l.py installation issue

### ISSUE THREAD

**Issue by sanjaradylov** [d2l-ai/d2l-en#712]
I have installed d2l-0.11.2 (the latest version so far) using pip as it was suggested in [Installation](https://d2l.ai/chapter_installation/index.html). When I attempted to run `d2l.Vocab` from [Machine Translation and the Dataset](https://github.com/d2l-ai/d2l-en/blob/master/chapter_recurrent-modern/machine-translation.md#vocabulary), I got
```python
TypeError: __init__() got an unexpected keyword argument 'reserved_tokens'
```
I turned to the source code of d2l package installed in my conda environment and compared it with [github repository of d2l](https://github.com/d2l-ai/d2l-en/tree/master/d2l). While both `__init__.py` files look the same, there are significant differences between `d2l.py` files. Specifically, `d2l.Vocab` in my local environment is not updated and it still accepts an old `use_special_tokens` parameter. So the modifications from 431305ab2628a69fad82464a8911eded16ea6ec9 were not committed. Also, many other newer objects (e.g. from d235bf132406f83a8e9b159fdf9a3b1434774ad0) are not included.
I tried to uninstall the previous version of d2l and reinstall the newest one, but it did not help. I had no issues with previous versions. Is there something wrong with repository/package configurations?

**Comment by astonzhang** [comment]
Thanks. I just uploaded the latest d2l source to pypi. You may do `pip install d2l --upgrade` now.

We keep editing the source file of d2l and only regularly upload such changes to the pypi package. Next time when you encounter similar problems, you may install from source, which may have not been uploaded to pypi yet:

```
pip uninstall d2l
pip install git+https://github.com/d2l-ai/d2l-en
```
