### ISSUE TITLE
ERROR : pip install git+https://github.com/d2l-ai/d2l-en

### ISSUE THREAD

**Issue by xiaojidan** [d2l-ai/d2l-en#766]
When I enter 'pip install git+https://github.com/d2l-ai/d2l-en', it shows that 

"`Cloning https://github.com/d2l-ai/d2l-en to /private/var/folders/42/wvdnbdv97t36hl2tbpl7qnhm0000gn/T/pip-req-build-3ifoib73
  Running command git clone -q https://github.com/d2l-ai/d2l-en /private/var/folders/42/wvdnbdv97t36hl2tbpl7qnhm0000gn/T/pip-req-build-3ifoib73
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
ERROR: Command errored out with exit status 128: git clone -q https://github.com/d2l-ai/d2l-en /private/var/folders/42/wvdnbdv97t36hl2tbpl7qnhm0000gn/T/pip-req-build-3ifoib73 Check the logs for full command output.`

what's wrong?

**Comment by astonzhang** [comment]
I tested `pip install git+https://github.com/d2l-ai/d2l-en` on my end and it still works. Did you google the error?
Alternatively, you may
option 1) `pip install d2l`
option 2) `git@github.com:d2l-ai/d2l-en.git && cd d2l-en && python setup.py --develop`

**Comment by xiaojidan** [comment]
@astonzhang  Thanks a lot . I solve it by your suggestions.
