### ISSUE TITLE
Correct method of making changes?

### ISSUE THREAD

**Issue by gregbruss** [d2l-ai/d2l-en#774]
Hi, first time contributor here. I've made some changes to my local (forked) repo on the MLP chapter, and then committed these changes to my fork and pushed it.

When I opened a pull request, it seems to have confused github as I see large diffs between our versions, and it fails some of the CI tests. I just reworded a couple sentences and fixed some typos

![image](https://user-images.githubusercontent.com/32633343/76165217-846be780-6155-11ea-846b-1b8a0dd0b874.png)

How do I avoid this situation?

**Comment by astonzhang** [comment]
See my comments in https://github.com/d2l-ai/d2l-en/pull/771
