### ISSUE TITLE
error in last code block of 8.5 (RNN from scratch)?

### ISSUE THREAD

**Issue by cvdelannoy** [d2l-ai/d2l-en#780]
If you run notebook 8.5 and you arrive at the last code block, a model should be trained where state is re-initialized at the start of each epoch:
```
train_ch8(model, train_iter, vocab, lr, num_epochs, ctx, use_random_iter=True)
```

However if you run the code as-is, it will take the model generated from the previous code block:
```
num_epochs, lr = 500, 1
train_ch8(model, train_iter, vocab, lr, num_epochs, ctx)
```
and continue training that one. Is this an error or was this as it was meant to be? I'm afraid I don't understand which one it should be from the text, and either is insightful (as the model output does change in a meaningful manner if you continue training the same model). If I had to choose one I'd rather compare a fresh model with re-initialized state per epoch to a fresh model without, in which case the last code block could read:
```
model = RNNModelScratch(len(vocab), num_hiddens, ctx, get_params,
                        init_rnn_state, rnn)
train_ch8(model, train_iter, vocab, lr, num_epochs, ctx, use_random_iter=True)
```

**Comment by astonzhang** [comment]
In Jupyter notebook, it is expected that "it will take the model generated from the previous code block" "and continue training that one". If you want to train a fresh model, you need to do re-initialize `model` before invoking `train_ch8`

**Comment by cvdelannoy** [comment]
Okay, if it should be like that I'm closing. Thanks for clarifying!
