### ISSUE TITLE
Typo in chapter Preliminaries in Probability part

### ISSUE THREAD

**Issue by Momentum-TN** [d2l-ai/d2l-en#795]
Hello, I am using the book for refreshing my mind. 
I have found a typo: "Say that we cast a DICE...." not a die

it has been repeated 22 times in the chapter.

Thank you for your effort for making ML free to learn.

**Comment by astonzhang** [comment]
Thanks. Do you want to send a PR to fix them:
https://d2l.ai/chapter_appendix-tools-for-deep-learning/contributing.html
