### ISSUE TITLE
MXNet Nightly Builds Moved to S3

### ISSUE THREAD

**Issue by szha** [d2l-ai/d2l-en#796]
Hi,

MXNet nightly builds have been moved from PyPI to S3 (https://github.com/pypa/pypi-support/issues/243). If this project requires the nightly builds for CI validation, please make sure that your CI pipeline now takes the nightly builds from https://dist.mxnet.io/python. Furthermore, as MXNet [1.7](https://github.com/apache/incubator-mxnet/issues/16864) and [2.0](https://github.com/apache/incubator-mxnet/issues/16167) are currently in progress simultaneously, we are releasing nightly builds for both 1.x and 2.x. Take `mxnet-cu102` for example:

If you need the nightly builds for 1.x:
```
pip install --pre "mxnet-cu102<2" -f https://dist.mxnet.io/python
```

If you need the nightly builds for 2.x:
```
pip install --pre "mxnet-cu102>=2" -f https://dist.mxnet.io/python
```

Feel free to close this issue if the necessary changes have been made, or If the project doesn't rely on MXNet nightly builds. Thanks.

**Comment by szha** [comment]
@astonzhang checking in. is the infra change ready?

**Comment by astonzhang** [comment]
We currently use released version. I'll close it. Thanks for the heads up!
