### ISSUE TITLE
Fix graphic [d2l-en/img/vgg.svg]

### ISSUE THREAD

**Issue by paulaurel** [d2l-ai/d2l-en#798]
The VGG network uses a MaxPooling layer with a 2x2 kernel not a 3x3 kernel.

**Comment by goldmermaid** [comment]
Hi @paulaurel , great catch! Thanks for @cuongvng corrected the text. I made the plot changes as well at PR https://github.com/d2l-ai/d2l-en/pull/881

**Comment by astonzhang** [comment]
Thanks. Closing since it's fixed
