### ISSUE TITLE
Wrong citation in Chapter recommender system

### ISSUE THREAD

**Issue by graytowne** [d2l-ai/d2l-en#800]
Hi d2l authors,

I found a minor mistake in the [chapter of recommender system](https://github.com/d2l-ai/d2l-en/blob/master/chapter_recommender-systems/seqrec.md):
The citation link for Caser is wrong:
```
Caser :cite:Sedhain.Menon.Sanner.ea.2015
```
,which should be:
```
Caser :cite:Tang.Wang.2018
```
Thanks for providing this high-quality content. Also, as a author of the mentioned method, I really appreciate it could be introduced in this valuable book.

**Comment by astonzhang** [comment]
Hi Jiaxi, thanks for spotting it and your great work on Caser!
Do you mind [sending a PR](https://d2l.ai/chapter_appendix-tools-for-deep-learning/contributing.html) to fix it?

**Comment by graytowne** [comment]
Sure thing, here's the PR: #801.
