### ISSUE TITLE
Error: module 'd2l' has no attribute 'train_ch5'

### ISSUE THREAD

**Issue by Guiming** [d2l-ai/d2l-en#806]
I was following the Feb 2020 version of the book, tried running alexnet.ipynb (chapter_convolutional-modern) and got this error: module 'd2l' has no attribute 'train_ch5'. 
This error is from 

d2l.train_ch5(net, train_iter, test_iter, num_epochs, lr)

It seems the d2l module does not include the train_ch5 function.

**Comment by astonzhang** [comment]
Since the book is still under development, we only track major changes in each [release](https://github.com/d2l-ai/d2l-en/releases).

If you are reading the latest version, it uses `train_ch6` now:
http://d2l.ai/chapter_convolutional-modern/alexnet.html

If you use any of the previously released version, you may follow the instruction section and still be able to run its code.

**Comment by Guai111** [comment]
Hi, I may encounter the same problem. In the chapter_preliminaries, a new function "plot" has been defined and "#@save" into d2l (which is in "section calculas"). But when I use `d2l.plot()`, it gives me `AttributeError :  module 'd2l' has no attribute 'plot'`.

**Comment by astonzhang** [comment]
> Hi, I may encounter the same problem. In the chapter_preliminaries, a new function "plot" has been defined and "#@save" into d2l (which is in "section calculas"). But when I use `d2l.plot()`, it gives me `AttributeError : module 'd2l' has no attribute 'plot'`.

Can you re-install `d2l`: `pip install d2l --upgrade`

**Comment by helloworldcty** [comment]
> > Hi, I may encounter the same problem. In the chapter_preliminaries, a new function "plot" has been defined and "#@save" into d2l (which is in "section calculas"). But when I use `d2l.plot()`, it gives me `AttributeError : module 'd2l' has no attribute 'plot'`.
> 
> Can you re-install `d2l`: `pip install d2l --upgrade`

I try re-install the d2l, but it also has this problem

**Comment by astonzhang** [comment]
Update: plz try `pip install d2l==0.17.5` since 1.0 will introduce breaking changes

**Comment by Wesady** [comment]
> Update: plz try `pip install d2l==0.17.5` since 1.0 will introduce breaking changes

HI, no matter whether I try `pip install d2l==0.17.5` or `pip install d2l --upgrade`, it doesn't work.

**Comment by Wesady** [comment]
> > Update: plz try `pip install d2l==0.17.5` since 1.0 will introduce breaking changes
> 
> HI, no matter whether I try `pip install d2l==0.17.5` or `pip install d2l --upgrade`, it doesn't work.

My problem, I used the wrong import method(`import d2l`), on the contrary, `from d2l import torch as d2l` should be used.
