### ISSUE TITLE
Typo in Figure  d2l-en/chapter_attention-mechanisms/seq2seq-attention.md 

### ISSUE THREAD

**Issue by sergulaydore** [d2l-ai/d2l-en#810]
The content should be context and also the outputs of decoder are coded as encoder outputs.

**Comment by goldmermaid** [comment]
Hi @sergulaydore , good catch! I have made changes in the PR https://github.com/d2l-ai/d2l-en/pull/882

**Comment by astonzhang** [comment]
Closing since it's fixed.
