### ISSUE TITLE
What infrastructure do you use to build this site?

### ISSUE THREAD

**Issue by choldgraf** [d2l-ai/d2l-en#852]
Hey there 👋 - this is a really amazing resource! I work on an open source project called [Jupyter Book](https://jupyterbook.org) that builds books similar to this one, and I am really curious what your build / website infrastructure looks like! Trying to see if I can find some pieces of inspiration in your infra :-)

**Comment by astonzhang** [comment]
Thanks. Just check out http://book.d2l.ai/

**Comment by choldgraf** [comment]
Very cool - thanks for the link. Just FYI Jupyter Book actually now uses Sphinx entirely for building books as well - we just finished a total re-write: check out the docs if you're curious (jupyterbook.org)
