### ISSUE TITLE
Little understanding issue in 8.1

### ISSUE THREAD

**Issue by Alexander-Schiendorfer** [d2l-ai/d2l-en#855]
I am a litte confused by the following paragraph
> It is much harder to predict tomorrow’s stock prices than to fill in the blanks for a stock price we missed yesterday, even though both are just a matter of estimating one number. After all, hindsight is so much easier than foresight. In statistics the former is called extrapolation whereas the latter is called interpolation. 

Isn't the former (hindsight) called **intrapolation** and the latter (foresight) called **extrapolation**. So, the other way around?

**Comment by goldmermaid** [comment]
Hey @Alexander-Schiendorfer , great catch! I have made a PR through https://github.com/d2l-ai/d2l-en/pull/878

**Comment by astonzhang** [comment]
Thanks @Alexander-Schiendorfer and @goldmermaid, I made some further edits:
https://github.com/d2l-ai/d2l-en/commit/8402f99660acb6fa1a1cc0cb67bbde0b947fe788
