### ISSUE TITLE
[Website] Table of contents incorrectly displayed

### ISSUE THREAD

**Issue by ChaiBapchya** [d2l-ai/d2l-en#902]
https://d2l.ai/chapter_computer-vision/image-augmentation.html
![Screen Shot 2020-05-26 at 7 38 54 AM](https://user-images.githubusercontent.com/10992635/82914186-0a612880-9f24-11ea-98c4-1fee6ade500c.png)

https://d2l.ai/chapter_computer-vision/rcnn.html
![Screen Shot 2020-05-26 at 7 39 02 AM](https://user-images.githubusercontent.com/10992635/82914248-1d73f880-9f24-11ea-9ce8-c608e3b8311c.png)

As you can see from the images, table of contents gets incorrectly aligned at the right side on Firefox browser
Confirmed same issue exists on Chrome & Safari as well.

**Comment by mli** [comment]
fixed

**Comment by ChaiBapchya** [comment]
Thanks. Curious to know which commit fixed it.
