### ISSUE TITLE
Number of parameters in Transformer

### ISSUE THREAD

**Issue by SoojungHong** [d2l-ai/d2l-en#929]
Hi, All 

I want to count the number of trainable parameters in Transformer. 
In PyTorch, there is a function (e.g. encoder.parameters()) to get the number of parameter. 
But it seems that d2l.EncoderDecoder(TransformerEncoder, TransformerDecoder) doesn't provide this kind of function. 
The reference model is following Transformer. 
https://d2l.ai/chapter_attention-mechanisms/transformer.html

Anyone know how to count the parameter number in Transformer?

**Comment by AnirudhDagar** [comment]
You can try using `collect_params()` for any network and loop over the params like this:
```python
num_params = 0
for p in net.collect_params().values():
    num_params += np.prod(np.array(p.data().shape))
```
Not sure if a more concise/easier method exists. But this should work.

**Comment by SoojungHong** [comment]
Thank you so much. 
I could count parameters with your advice.

**Comment by goldmermaid** [comment]
Hey @SoojungHong , could you close this issue if everything is clear?

**Comment by SoojungHong** [comment]
ok, thanks a lot for your help!
