### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by manuel-arno-korfmann-webentwicklung** [d2l-ai/d2l-en#935]
Is a german translation already in the progress somewhere?

I've [started translating a few sentences of the preface to german](https://github.com/manuel-arno-korfmann-webentwicklung/d2l-de/pull/1/files) and wondered if this is something already pursued by someone else.

**Comment by goldmermaid** [comment]
Hi @manuel-arno-korfmann-webentwicklung , we haven't started translating to German yet. If you seriously decide to volunteer, we can guide you through the process.

**Comment by astonzhang** [comment]
Thanks for the interest! Currently we are still editing the entire book like crazy. For translation repo, there are two options:

option 1: start translation right now based on a stable release (most stable release is https://github.com/d2l-ai/d2l-en/releases/tag/v0.8.0). While we are still editing text and code every day, when there's a new release, `git diff` so you can translate those changes. You may start working on translating the first 7 chapters on your own repo. Then we can build stuff from there. Pro: you can start right away; Con: you may waste time in going back and forth to translate the same notebook for multiple times as long as there are edits there. 

option 2: just wait until the book is finished then start translation.
