### ISSUE TITLE
Reading group via online video chat

### ISSUE THREAD

**Issue by manuel-arno-korfmann-webentwicklung** [d2l-ai/d2l-en#936]
We would take turns reading the material and discuss after every passage to help with understanding and also attempt to solve exercises together.

**Comment by manuel-arno-korfmann-webentwicklung** [comment]
https://coursera.community/artificial-intelligence-ai-64/reading-group-for-dive-into-deep-learning-book-https-d2l-ai-10414

**Comment by smolix** [comment]
That's awesome if you do this. Why don't you record the videos and post them on YouTube. I'm sure it'll help others, too.

**Comment by manuel-arno-korfmann-webentwicklung** [comment]
> That's awesome if you do this. Why don't you record the videos and post them on YouTube. I'm sure it'll help others, too.

That is a good idea, I will try to get that started.

I also created a MailChimp newsletter to keep people up to date with the reading group's schedule:

https://247reading.group

**Comment by manuel-arno-korfmann-webentwicklung** [comment]
@smolix The link to the first (partially) recorded session's video: https://us10.campaign-archive.com/?u=f6f2e1610af661ab8230eab77&id=29786ffa00 (Youtube link is just at the beginning of the message, it's a bit confusing since the campaign-archive doesn't seem to show the subject line)
