### ISSUE TITLE
Issue with plot titles in Section 18.6.1.6

### ISSUE THREAD

**Issue by AnirudhDagar** [d2l-ai/d2l-en#974]
In section [18.6.1.6. Standard Deviations](https://d2l.ai/chapter_appendix-mathematics-for-deep-learning/random-variables.html#standard-deviations) the three different plots with different probabilities show the same title i.e. `p>1/8`.

This should be resolved to `p>1/8, p=1/8,  p<1/8` for the 3 plots respectively.
We need to update `plt.title` for this. I'll send in a PR to fix this issue.

**Comment by astonzhang** [comment]
@bwerness

**Comment by AnirudhDagar** [comment]
@astonzhang Do you want me to send in a fix?

**Comment by bwerness** [comment]
I think if you just change it from
`d2l.plt.title("p > 1/8")`
to
`d2l.plt.title("p > {}".format(p))`
or similar should resolve this.

**Comment by bwerness** [comment]
Send in the fix IMO.
